from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QApplication, QPushButton, QVBoxLayout, QTabWidget, QHBoxLayout, QGroupBox, QLabel, QSlider, QLCDNumber, QSizePolicy, QSpacerItem, QTableView, QStatusBar, QAction, QDialog, QWidget, QLineEdit, QDialogButtonBox, QFormLayout, QDataWidgetMapper \
							, QFrame, QDateEdit, QCheckBox, QComboBox
try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName(_fromUtf8("MainWindow"))
		MainWindow.resize(1920, 1200)
		self.centralwidget = QWidget(MainWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.horizontalLayout = QHBoxLayout(self.centralwidget)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.verticalLayout = QVBoxLayout()
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.ptabWidget = QTabWidget(self.centralwidget)
		palette = QtGui.QPalette()
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
		brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
		brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
		brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
		brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
		brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
		brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
		brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
		brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
		brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
		brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
		brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
		brush.setStyle(QtCore.Qt.SolidPattern)
		palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
		self.ptabWidget.setPalette(palette)
		self.ptabWidget.setObjectName(_fromUtf8("ptabWidget"))
		self.tabPolygon = QWidget()
		self.tabPolygon.setObjectName(_fromUtf8("tabPolygon"))
		self.horizontalLayout_2 = QHBoxLayout(self.tabPolygon)
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.verticalLayout_2 = QVBoxLayout()
		self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
		self.verticalLayout_10 = QVBoxLayout()
		self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
		self.groupBox_5 = QGroupBox(self.tabPolygon)
		self.groupBox_5.setEnabled(True)
		self.groupBox_5.setTitle(_fromUtf8(""))
		self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
		self.floor_02 = QLabel(self.groupBox_5)
		self.floor_02.setObjectName(u"floor_02")
		self.floor_02.setGeometry(QtCore.QRect(350, 350, 100, 100))
		self.floor_02.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_02.setTextFormat(QtCore.Qt.PlainText)
		self.floor_02.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_03 = QLabel(self.groupBox_5)
		self.floor_03.setObjectName(u"floor_03")
		self.floor_03.setGeometry(QtCore.QRect(250, 350, 100, 100))
		self.floor_03.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_03.setTextFormat(QtCore.Qt.PlainText)
		self.floor_03.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_04 = QLabel(self.groupBox_5)
		self.floor_04.setObjectName(u"floor_04")
		self.floor_04.setGeometry(QtCore.QRect(250, 450, 100, 100))
		self.floor_04.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_04.setTextFormat(QtCore.Qt.PlainText)
		self.floor_04.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_05 = QLabel(self.groupBox_5)
		self.floor_05.setObjectName(u"floor_05")
		self.floor_05.setGeometry(QtCore.QRect(150, 450, 100, 100))
		self.floor_05.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_05.setTextFormat(QtCore.Qt.PlainText)
		self.floor_05.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_06 = QLabel(self.groupBox_5)
		self.floor_06.setObjectName(u"floor_06")
		self.floor_06.setGeometry(QtCore.QRect(50, 450, 100, 100))
		self.floor_06.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_06.setTextFormat(QtCore.Qt.PlainText)
		self.floor_06.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_07 = QLabel(self.groupBox_5)
		self.floor_07.setObjectName(u"floor_07")
		self.floor_07.setGeometry(QtCore.QRect(50, 350, 100, 100))
		self.floor_07.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_07.setTextFormat(QtCore.Qt.PlainText)
		self.floor_07.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_08 = QLabel(self.groupBox_5)
		self.floor_08.setObjectName(u"floor_08")
		self.floor_08.setGeometry(QtCore.QRect(150, 350, 100, 100))
		self.floor_08.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_08.setTextFormat(QtCore.Qt.PlainText)
		self.floor_08.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_09 = QLabel(self.groupBox_5)
		self.floor_09.setObjectName(u"floor_09")
		self.floor_09.setGeometry(QtCore.QRect(150, 250, 100, 100))
		self.floor_09.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_09.setTextFormat(QtCore.Qt.PlainText)
		self.floor_09.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_10 = QLabel(self.groupBox_5)
		self.floor_10.setObjectName(u"floor_10")
		self.floor_10.setGeometry(QtCore.QRect(50, 250, 100, 100))
		self.floor_10.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_10.setTextFormat(QtCore.Qt.PlainText)
		self.floor_10.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_11 = QLabel(self.groupBox_5)
		self.floor_11.setObjectName(u"floor_11")
		self.floor_11.setGeometry(QtCore.QRect(50, 150, 100, 100))
		self.floor_11.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_11.setTextFormat(QtCore.Qt.PlainText)
		self.floor_11.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_12 = QLabel(self.groupBox_5)
		self.floor_12.setObjectName(u"floor_12")
		self.floor_12.setGeometry(QtCore.QRect(50, 50, 100, 100))
		self.floor_12.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_12.setTextFormat(QtCore.Qt.PlainText)
		self.floor_12.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_13 = QLabel(self.groupBox_5)
		self.floor_13.setObjectName(u"floor_13")
		self.floor_13.setGeometry(QtCore.QRect(150, 50, 100, 100))
		self.floor_13.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_13.setTextFormat(QtCore.Qt.PlainText)
		self.floor_13.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_14 = QLabel(self.groupBox_5)
		self.floor_14.setObjectName(u"floor_14")
		self.floor_14.setGeometry(QtCore.QRect(150, 150, 100, 100))
		self.floor_14.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_14.setTextFormat(QtCore.Qt.PlainText)
		self.floor_14.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_15 = QLabel(self.groupBox_5)
		self.floor_15.setObjectName(u"floor_15")
		self.floor_15.setGeometry(QtCore.QRect(250, 150, 100, 100))
		self.floor_15.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_15.setTextFormat(QtCore.Qt.PlainText)
		self.floor_15.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_16 = QLabel(self.groupBox_5)
		self.floor_16.setObjectName(u"floor_16")
		self.floor_16.setGeometry(QtCore.QRect(250, 50, 100, 100))
		self.floor_16.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_16.setTextFormat(QtCore.Qt.PlainText)
		self.floor_16.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_17 = QLabel(self.groupBox_5)
		self.floor_17.setObjectName(u"floor_17")
		self.floor_17.setGeometry(QtCore.QRect(350, 50, 100, 100))
		self.floor_17.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_17.setTextFormat(QtCore.Qt.PlainText)
		self.floor_17.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_18 = QLabel(self.groupBox_5)
		self.floor_18.setObjectName(u"floor_18")
		self.floor_18.setGeometry(QtCore.QRect(350, 150, 100, 100))
		self.floor_18.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_18.setTextFormat(QtCore.Qt.PlainText)
		self.floor_18.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_19 = QLabel(self.groupBox_5)
		self.floor_19.setObjectName(u"floor_19")
		self.floor_19.setGeometry(QtCore.QRect(450, 150, 100, 100))
		self.floor_19.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_19.setTextFormat(QtCore.Qt.PlainText)
		self.floor_19.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_20 = QLabel(self.groupBox_5)
		self.floor_20.setObjectName(u"floor_20")
		self.floor_20.setGeometry(QtCore.QRect(550, 150, 100, 100))
		self.floor_20.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_20.setTextFormat(QtCore.Qt.PlainText)
		self.floor_20.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_01 = QLabel(self.groupBox_5)
		self.floor_01.setObjectName(u"floor_01")
		self.floor_01.setGeometry(QtCore.QRect(350, 450, 100, 100))
		self.floor_01.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_01.setTextFormat(QtCore.Qt.PlainText)
		self.floor_01.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_21 = QLabel(self.groupBox_5)
		self.floor_21.setObjectName(u"floor_21")
		self.floor_21.setGeometry(QtCore.QRect(550, 250, 100, 100))
		self.floor_21.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_21.setTextFormat(QtCore.Qt.PlainText)
		self.floor_21.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_22 = QLabel(self.groupBox_5)
		self.floor_22.setObjectName(u"floor_22")
		self.floor_22.setGeometry(QtCore.QRect(550, 350, 100, 100))
		self.floor_22.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_22.setTextFormat(QtCore.Qt.PlainText)
		self.floor_22.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_23 = QLabel(self.groupBox_5)
		self.floor_23.setObjectName(u"floor_23")
		self.floor_23.setGeometry(QtCore.QRect(650, 350, 100, 100))
		self.floor_23.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_23.setTextFormat(QtCore.Qt.PlainText)
		self.floor_23.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_24 = QLabel(self.groupBox_5)
		self.floor_24.setObjectName(u"floor_24")
		self.floor_24.setGeometry(QtCore.QRect(650, 250, 100, 100))
		self.floor_24.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_24.setTextFormat(QtCore.Qt.PlainText)
		self.floor_24.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_25 = QLabel(self.groupBox_5)
		self.floor_25.setObjectName(u"floor_25")
		self.floor_25.setGeometry(QtCore.QRect(650, 150, 100, 100))
		self.floor_25.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_25.setTextFormat(QtCore.Qt.PlainText)
		self.floor_25.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_26 = QLabel(self.groupBox_5)
		self.floor_26.setObjectName(u"floor_26")
		self.floor_26.setGeometry(QtCore.QRect(750, 150, 100, 100))
		self.floor_26.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_26.setTextFormat(QtCore.Qt.PlainText)
		self.floor_26.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_27 = QLabel(self.groupBox_5)
		self.floor_27.setObjectName(u"floor_27")
		self.floor_27.setGeometry(QtCore.QRect(850, 150, 100, 100))
		self.floor_27.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_27.setTextFormat(QtCore.Qt.PlainText)
		self.floor_27.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_28 = QLabel(self.groupBox_5)
		self.floor_28.setObjectName(u"floor_28")
		self.floor_28.setGeometry(QtCore.QRect(950, 150, 100, 100))
		self.floor_28.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_28.setTextFormat(QtCore.Qt.PlainText)
		self.floor_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
		self.floor_29 = QLabel(self.groupBox_5)
		self.floor_29.setObjectName(u"floor_29")
		self.floor_29.setGeometry(QtCore.QRect(950, 50, 100, 100))
		self.floor_29.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_29.setTextFormat(QtCore.Qt.PlainText)
		self.floor_29.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.floor_30 = QLabel(self.groupBox_5)
		self.floor_30.setObjectName(u"floor_30")
		self.floor_30.setGeometry(QtCore.QRect(850, 50, 100, 100))
		self.floor_30.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_30.setTextFormat(QtCore.Qt.PlainText)
		self.floor_30.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.floor_31 = QLabel(self.groupBox_5)
		self.floor_31.setObjectName(u"floor_31")
		self.floor_31.setGeometry(QtCore.QRect(880, 20, 100, 100))
		self.floor_31.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_31.setTextFormat(QtCore.Qt.PlainText)
		self.floor_31.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_32 = QLabel(self.groupBox_5)
		self.floor_32.setObjectName(u"floor_32")
		self.floor_32.setGeometry(QtCore.QRect(980, 20, 100, 100))
		self.floor_32.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_32.setTextFormat(QtCore.Qt.PlainText)
		self.floor_32.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_33 = QLabel(self.groupBox_5)
		self.floor_33.setObjectName(u"floor_33")
		self.floor_33.setGeometry(QtCore.QRect(980, 190, 100, 100))
		self.floor_33.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_33.setTextFormat(QtCore.Qt.PlainText)
		self.floor_33.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_34 = QLabel(self.groupBox_5)
		self.floor_34.setObjectName(u"floor_34")
		self.floor_34.setGeometry(QtCore.QRect(1080, 190, 100, 100))
		self.floor_34.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_34.setTextFormat(QtCore.Qt.PlainText)
		self.floor_34.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_36 = QLabel(self.groupBox_5)
		self.floor_36.setObjectName(u"floor_36")
		self.floor_36.setGeometry(QtCore.QRect(1150, 50, 100, 100))
		self.floor_36.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_36.setTextFormat(QtCore.Qt.PlainText)
		self.floor_36.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_37 = QLabel(self.groupBox_5)
		self.floor_37.setObjectName(u"floor_37")
		self.floor_37.setGeometry(QtCore.QRect(1050, 50, 100, 100))
		self.floor_37.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_37.setTextFormat(QtCore.Qt.PlainText)
		self.floor_37.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.floor_38 = QLabel(self.groupBox_5)
		self.floor_38.setObjectName(u"floor_38")
		self.floor_38.setGeometry(QtCore.QRect(1050, 150, 100, 100))
		self.floor_38.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_38.setTextFormat(QtCore.Qt.PlainText)
		self.floor_38.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.floor_39 = QLabel(self.groupBox_5)
		self.floor_39.setObjectName(u"floor_39")
		self.floor_39.setGeometry(QtCore.QRect(1050, 250, 100, 100))
		self.floor_39.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_39.setFrameShape(QFrame.NoFrame)
		self.floor_39.setTextFormat(QtCore.Qt.PlainText)
		self.floor_39.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.floor_40 = QLabel(self.groupBox_5)
		self.floor_40.setObjectName(u"floor_40")
		self.floor_40.setGeometry(QtCore.QRect(1080, 320, 100, 100))
		self.floor_40.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_40.setTextFormat(QtCore.Qt.PlainText)
		self.floor_40.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_41 = QLabel(self.groupBox_5)
		self.floor_41.setObjectName(u"floor_41")
		self.floor_41.setGeometry(QtCore.QRect(1180, 320, 100, 100))
		self.floor_41.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_41.setTextFormat(QtCore.Qt.PlainText)
		self.floor_41.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_42 = QLabel(self.groupBox_5)
		self.floor_42.setObjectName(u"floor_42")
		self.floor_42.setGeometry(QtCore.QRect(1150, 250, 100, 100))
		self.floor_42.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_42.setTextFormat(QtCore.Qt.PlainText)
		self.floor_42.setAlignment(QtCore.Qt.AlignCenter)
		self.roura = QLabel(self.groupBox_5)
		self.roura.setObjectName(u"roura")
		self.roura.setGeometry(QtCore.QRect(1150, 350, 100, 100))
		self.roura.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.roura.setTextFormat(QtCore.Qt.PlainText)
		self.roura.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
		self.floor_43 = QLabel(self.groupBox_5)
		self.floor_43.setObjectName(u"floor_43")
		self.floor_43.setGeometry(QtCore.QRect(1150, 450, 100, 100))
		self.floor_43.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_43.setTextFormat(QtCore.Qt.PlainText)
		self.floor_43.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_44 = QLabel(self.groupBox_5)
		self.floor_44.setObjectName(u"floor_44")
		self.floor_44.setGeometry(QtCore.QRect(1050, 450, 100, 100))
		self.floor_44.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_44.setTextFormat(QtCore.Qt.PlainText)
		self.floor_44.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_45 = QLabel(self.groupBox_5)
		self.floor_45.setObjectName(u"floor_45")
		self.floor_45.setGeometry(QtCore.QRect(1050, 350, 100, 100))
		self.floor_45.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_45.setTextFormat(QtCore.Qt.PlainText)
		self.floor_45.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
		self.floor_46 = QLabel(self.groupBox_5)
		self.floor_46.setObjectName(u"floor_46")
		self.floor_46.setGeometry(QtCore.QRect(1610, 20, 100, 100))
		self.floor_46.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_46.setTextFormat(QtCore.Qt.PlainText)
		self.floor_46.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_47 = QLabel(self.groupBox_5)
		self.floor_47.setObjectName(u"floor_47")
		self.floor_47.setGeometry(QtCore.QRect(1610, 120, 100, 100))
		self.floor_47.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_47.setTextFormat(QtCore.Qt.PlainText)
		self.floor_47.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_48 = QLabel(self.groupBox_5)
		self.floor_48.setObjectName(u"floor_48")
		self.floor_48.setGeometry(QtCore.QRect(1710, 120, 100, 100))
		self.floor_48.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_48.setTextFormat(QtCore.Qt.PlainText)
		self.floor_48.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_49 = QLabel(self.groupBox_5)
		self.floor_49.setObjectName(u"floor_49")
		self.floor_49.setGeometry(QtCore.QRect(1710, 220, 100, 100))
		self.floor_49.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_49.setTextFormat(QtCore.Qt.PlainText)
		self.floor_49.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_50 = QLabel(self.groupBox_5)
		self.floor_50.setObjectName(u"floor_50")
		self.floor_50.setGeometry(QtCore.QRect(1710, 320, 100, 100))
		self.floor_50.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_50.setTextFormat(QtCore.Qt.PlainText)
		self.floor_50.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_51 = QLabel(self.groupBox_5)
		self.floor_51.setObjectName(u"floor_51")
		self.floor_51.setGeometry(QtCore.QRect(1710, 420, 100, 100))
		self.floor_51.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_51.setTextFormat(QtCore.Qt.PlainText)
		self.floor_51.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_52 = QLabel(self.groupBox_5)
		self.floor_52.setObjectName(u"floor_52")
		self.floor_52.setGeometry(QtCore.QRect(1710, 520, 100, 100))
		self.floor_52.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_52.setTextFormat(QtCore.Qt.PlainText)
		self.floor_52.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_53 = QLabel(self.groupBox_5)
		self.floor_53.setObjectName(u"floor_53")
		self.floor_53.setGeometry(QtCore.QRect(1610, 520, 100, 100))
		self.floor_53.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_53.setTextFormat(QtCore.Qt.PlainText)
		self.floor_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.floor_54 = QLabel(self.groupBox_5)
		self.floor_54.setObjectName(u"floor_54")
		self.floor_54.setGeometry(QtCore.QRect(1640, 190, 100, 100))
		self.floor_54.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_54.setTextFormat(QtCore.Qt.PlainText)
		self.floor_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.floor_55 = QLabel(self.groupBox_5)
		self.floor_55.setObjectName(u"floor_55")
		self.floor_55.setGeometry(QtCore.QRect(1470, 150, 100, 100))
		self.floor_55.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_55.setTextFormat(QtCore.Qt.PlainText)
		self.floor_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.floor_56 = QLabel(self.groupBox_5)
		self.floor_56.setObjectName(u"floor_56")
		self.floor_56.setGeometry(QtCore.QRect(1570, 150, 100, 100))
		self.floor_56.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_56.setTextFormat(QtCore.Qt.PlainText)
		self.floor_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.floor_57 = QLabel(self.groupBox_5)
		self.floor_57.setObjectName(u"floor_57")
		self.floor_57.setGeometry(QtCore.QRect(1570, 250, 100, 100))
		self.floor_57.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_57.setTextFormat(QtCore.Qt.PlainText)
		self.floor_57.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_58 = QLabel(self.groupBox_5)
		self.floor_58.setObjectName(u"floor_58")
		self.floor_58.setGeometry(QtCore.QRect(1570, 350, 100, 100))
		self.floor_58.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_58.setTextFormat(QtCore.Qt.PlainText)
		self.floor_58.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_59 = QLabel(self.groupBox_5)
		self.floor_59.setObjectName(u"floor_59")
		self.floor_59.setGeometry(QtCore.QRect(1570, 450, 100, 100))
		self.floor_59.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_59.setTextFormat(QtCore.Qt.PlainText)
		self.floor_59.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_35 = QLabel(self.groupBox_5)
		self.floor_35.setObjectName(u"floor_35")
		self.floor_35.setGeometry(QtCore.QRect(1080, 20, 100, 100))
		self.floor_35.setStyleSheet("border: 1px solid gray;background-color: rgb(255, 255, 255);color:black;")
		self.floor_35.setTextFormat(QtCore.Qt.PlainText)
		self.floor_35.setAlignment(QtCore.Qt.AlignCenter)
		self.floor_59.raise_()
		self.floor_53.raise_()
		self.floor_55.raise_()
		self.floor_56.raise_()
		self.floor_57.raise_()
		self.floor_58.raise_()
		self.floor_54.raise_()
		self.floor_42.raise_()
		self.floor_39.raise_()
		self.floor_36.raise_()
		self.floor_37.raise_()
		self.floor_29.raise_()
		self.floor_38.raise_()
		self.floor_28.raise_()
		self.floor_45.raise_()
		self.roura.raise_()
		self.floor_02.raise_()
		self.floor_03.raise_()
		self.floor_04.raise_()
		self.floor_05.raise_()
		self.floor_06.raise_()
		self.floor_07.raise_()
		self.floor_08.raise_()
		self.floor_09.raise_()
		self.floor_10.raise_()
		self.floor_11.raise_()
		self.floor_12.raise_()
		self.floor_13.raise_()
		self.floor_14.raise_()
		self.floor_15.raise_()
		self.floor_16.raise_()
		self.floor_17.raise_()
		self.floor_18.raise_()
		self.floor_19.raise_()
		self.floor_20.raise_()
		self.floor_01.raise_()
		self.floor_21.raise_()
		self.floor_22.raise_()
		self.floor_23.raise_()
		self.floor_24.raise_()
		self.floor_25.raise_()
		self.floor_26.raise_()
		self.floor_27.raise_()
		self.floor_30.raise_()
		self.floor_31.raise_()
		self.floor_32.raise_()
		self.floor_33.raise_()
		self.floor_34.raise_()
		self.floor_40.raise_()
		self.floor_41.raise_()
		self.floor_43.raise_()
		self.floor_44.raise_()
		self.floor_46.raise_()
		self.floor_47.raise_()
		self.floor_48.raise_()
		self.floor_49.raise_()
		self.floor_50.raise_()
		self.floor_51.raise_()
		self.floor_52.raise_()
		self.floor_35.raise_()
		self.verticalLayout_10.addWidget(self.groupBox_5)
		self.verticalLayout_2.addLayout(self.verticalLayout_10)
		self.horizontalLayout_3 = QHBoxLayout()
		self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
		self.groupBox_4 = QGroupBox(self.tabPolygon)
		self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
		self.horizontalLayout_9 = QHBoxLayout(self.groupBox_4)
		self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
		self.horizontalLayout_8 = QHBoxLayout()
		self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
		self.horizontalLayout_11 = QHBoxLayout()
		self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
		self.verticalLayout_5 = QVBoxLayout()
		self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
		self.fan12Button = QPushButton(self.groupBox_4)
		self.fan12Button.setMinimumSize(QtCore.QSize(100, 60))
		self.fan12Button.setFocusPolicy(QtCore.Qt.NoFocus)
		self.fan12Button.setStyleSheet(_fromUtf8(""))
		self.fan12Button.setCheckable(True)
		self.fan12Button.setObjectName(_fromUtf8("fan12Button"))
		self.verticalLayout_5.addWidget(self.fan12Button)
		self.fan34Button = QPushButton(self.groupBox_4)
		self.fan34Button.setMinimumSize(QtCore.QSize(100, 60))
		self.fan34Button.setFocusPolicy(QtCore.Qt.NoFocus)
		self.fan34Button.setCheckable(True)
		self.fan34Button.setObjectName(_fromUtf8("fan34Button"))
		self.verticalLayout_5.addWidget(self.fan34Button)
		self.fanControlRoomButton = QPushButton(self.groupBox_4)
		self.fanControlRoomButton.setMinimumSize(QtCore.QSize(100, 60))
		self.fanControlRoomButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.fanControlRoomButton.setCheckable(True)
		self.fanControlRoomButton.setObjectName(_fromUtf8("fanControlRoomButton"))
		self.verticalLayout_5.addWidget(self.fanControlRoomButton)
		self.glowButton = QPushButton(self.groupBox_4)
		self.glowButton.setMinimumSize(QtCore.QSize(100, 60))
		self.glowButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.glowButton.setCheckable(True)
		self.glowButton.setObjectName(_fromUtf8("glowButton"))
		self.verticalLayout_5.addWidget(self.glowButton)
		self.horizontalLayout_11.addLayout(self.verticalLayout_5)
		self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
		self.horizontalLayout_12 = QHBoxLayout()
		self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
		self.verticalLayout_6 = QVBoxLayout()
		self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
		self.stroboButton = QPushButton(self.groupBox_4)
		self.stroboButton.setMinimumSize(QtCore.QSize(100, 60))
		self.stroboButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.stroboButton.setCheckable(True)
		self.stroboButton.setObjectName(_fromUtf8("stroboButton"))
		self.verticalLayout_6.addWidget(self.stroboButton)
		self.hotZoneButton = QPushButton(self.groupBox_4)
		self.hotZoneButton.setMinimumSize(QtCore.QSize(100, 60))
		self.hotZoneButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.hotZoneButton.setCheckable(True)
		self.hotZoneButton.setObjectName(_fromUtf8("hotZoneButton"))
		self.verticalLayout_6.addWidget(self.hotZoneButton)
		self.louverButton = QPushButton(self.groupBox_4)
		self.louverButton.setMinimumSize(QtCore.QSize(100, 60))
		self.louverButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.louverButton.setCheckable(True)
		self.louverButton.setObjectName(_fromUtf8("louverButton"))
		self.verticalLayout_6.addWidget(self.louverButton)
		self.smokeButton = QPushButton(self.groupBox_4)
		self.smokeButton.setMinimumSize(QtCore.QSize(100, 60))
		self.smokeButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.smokeButton.setCheckable(True)
		self.smokeButton.setObjectName(_fromUtf8("smokeButton"))
		self.verticalLayout_6.addWidget(self.smokeButton)
		self.horizontalLayout_12.addLayout(self.verticalLayout_6)
		self.horizontalLayout_8.addLayout(self.horizontalLayout_12)
		self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
		self.horizontalLayout_3.addWidget(self.groupBox_4)
		self.groupBox_3 = QGroupBox(self.tabPolygon)
		self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
		self.horizontalLayout_5 = QHBoxLayout(self.groupBox_3)
		self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
		self.horizontalLayout_4 = QHBoxLayout()
		self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
		self.horizontalLayout_6 = QHBoxLayout()
		self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
		self.verticalLayout_3 = QVBoxLayout()
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.polygonLight1Button = QPushButton(self.groupBox_3)
		self.polygonLight1Button.setMinimumSize(QtCore.QSize(100, 60))
		self.polygonLight1Button.setFocusPolicy(QtCore.Qt.NoFocus)
		self.polygonLight1Button.setCheckable(True)
		self.polygonLight1Button.setObjectName(_fromUtf8("polygonLight1Button"))
		self.verticalLayout_3.addWidget(self.polygonLight1Button)
		self.polygonLight2Button = QPushButton(self.groupBox_3)
		self.polygonLight2Button.setMinimumSize(QtCore.QSize(100, 60))
		self.polygonLight2Button.setFocusPolicy(QtCore.Qt.NoFocus)
		self.polygonLight2Button.setCheckable(True)
		self.polygonLight2Button.setObjectName(_fromUtf8("polygonLight2Button"))
		self.verticalLayout_3.addWidget(self.polygonLight2Button)
		self.polygonLight3Button = QPushButton(self.groupBox_3)
		self.polygonLight3Button.setMinimumSize(QtCore.QSize(100, 60))
		self.polygonLight3Button.setFocusPolicy(QtCore.Qt.NoFocus)
		self.polygonLight3Button.setCheckable(True)
		self.polygonLight3Button.setObjectName(_fromUtf8("polygonLight3Button"))
		self.verticalLayout_3.addWidget(self.polygonLight3Button)
		self.hotZoneLightButton = QPushButton(self.groupBox_3)
		self.hotZoneLightButton.setMinimumSize(QtCore.QSize(100, 60))
		self.hotZoneLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.hotZoneLightButton.setCheckable(True)
		self.hotZoneLightButton.setObjectName(_fromUtf8("hotZoneLightButton"))
		self.verticalLayout_3.addWidget(self.hotZoneLightButton)
		self.horizontalLayout_6.addLayout(self.verticalLayout_3)
		self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
		self.horizontalLayout_7 = QHBoxLayout()
		self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
		self.verticalLayout_4 = QVBoxLayout()
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.stressRoomLightButton = QPushButton(self.groupBox_3)
		self.stressRoomLightButton.setMinimumSize(QtCore.QSize(100, 60))
		self.stressRoomLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.stressRoomLightButton.setCheckable(True)
		self.stressRoomLightButton.setObjectName(_fromUtf8("stressRoomLightButton"))
		self.verticalLayout_4.addWidget(self.stressRoomLightButton)
		self.infraLightButton = QPushButton(self.groupBox_3)
		self.infraLightButton.setMinimumSize(QtCore.QSize(100, 60))
		self.infraLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.infraLightButton.setCheckable(True)
		self.infraLightButton.setObjectName(_fromUtf8("infraLightButton"))
		self.verticalLayout_4.addWidget(self.infraLightButton)
		self.controlRoomLightButton = QPushButton(self.groupBox_3)
		self.controlRoomLightButton.setMinimumSize(QtCore.QSize(100, 60))
		self.controlRoomLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.controlRoomLightButton.setCheckable(True)
		self.controlRoomLightButton.setObjectName(_fromUtf8("controlRoomLightButton"))
		self.verticalLayout_4.addWidget(self.controlRoomLightButton)
		self.helpLightButton = QPushButton(self.groupBox_3)
		self.helpLightButton.setMinimumSize(QtCore.QSize(100, 60))
		self.helpLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.helpLightButton.setCheckable(True)
		self.helpLightButton.setObjectName(_fromUtf8("helpLightButton"))
		self.verticalLayout_4.addWidget(self.helpLightButton)
		self.horizontalLayout_7.addLayout(self.verticalLayout_4)
		self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
		self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
		self.horizontalLayout_3.addWidget(self.groupBox_3)
		self.groupBox = QGroupBox(self.tabPolygon)
		self.groupBox.setObjectName(_fromUtf8("groupBox"))
		self.horizontalLayout_13 = QHBoxLayout(self.groupBox)
		self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
		self.verticalLayout_8 = QVBoxLayout()
		self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
		self.horizontalLayout_16 = QHBoxLayout()
		self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
		self.volumeSlider = QSlider(self.groupBox)
		self.volumeSlider.setProperty("value", 50)
		self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
		self.volumeSlider.setTickPosition(QSlider.TicksBothSides)
		self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
		sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
		self.volumeSlider.setSizePolicy(sizePolicy)
		self.horizontalLayout_16.addWidget(self.volumeSlider)
		self.verticalLayout_8.addLayout(self.horizontalLayout_16)
		self.pushButton_19 = QPushButton(self.groupBox)
		self.pushButton_19.setMinimumSize(QtCore.QSize(0, 60))
		self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
		self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
		self.verticalLayout_8.addWidget(self.pushButton_19)
		self.horizontalLayout_15 = QHBoxLayout()
		self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
		self.verticalLayout_8.addLayout(self.horizontalLayout_15)
		self.horizontalLayout_13.addLayout(self.verticalLayout_8)
		self.horizontalLayout_3.addWidget(self.groupBox)
		self.groupBox_6 = QGroupBox(self.tabPolygon)
		self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
		self.horizontalLayout_10 = QHBoxLayout(self.groupBox_6)
		self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
		self.verticalLayout_9 = QVBoxLayout()
		self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
		self.lcdNumber = QLCDNumber(self.groupBox_6)
		self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
		self.lcdNumber.setStyleSheet("color: rgb(243, 0, 0);background-color: rgb(60, 0, 0);")
		self.verticalLayout_9.addWidget(self.lcdNumber)
		self.emergencyButton = QPushButton(self.groupBox_6)
		self.emergencyButton.setMinimumSize(QtCore.QSize(0, 87))
		self.emergencyButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.emergencyButton.setObjectName(_fromUtf8("emergencyButton"))
		self.emergencyButton.setStyleSheet("background-color: rgb(255, 193, 7);color: rgb(255,255,255)")
		self.verticalLayout_9.addWidget(self.emergencyButton)
		self.horizontalLayout_17 = QHBoxLayout()
		self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
		self.startButton = QPushButton(self.groupBox_6)
		self.startButton.setMinimumSize(QtCore.QSize(0, 100))
		self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.startButton.setObjectName(_fromUtf8("startButton"))
		self.startButton.setStyleSheet("QPushButton {background-color: rgb(25,135,84);color: rgb(255,255,255)} QPushButton:disabled {background-color: rgba(92, 184, 92, 0.40)}")
		self.horizontalLayout_17.addWidget(self.startButton)
		self.stopButton = QPushButton(self.groupBox_6)
		self.stopButton.setMinimumSize(QtCore.QSize(0, 100))
		self.stopButton.setFocusPolicy(QtCore.Qt.NoFocus)
		self.stopButton.setObjectName(_fromUtf8("stopButton"))
		self.stopButton.setStyleSheet("QPushButton {background-color: rgb(220,53,69);color: rgb(255,255,255)} QPushButton:disabled {background-color: rgba(217,83,79, 0.40)}")
		self.horizontalLayout_17.addWidget(self.stopButton)
		self.verticalLayout_9.addLayout(self.horizontalLayout_17)
		self.horizontalLayout_10.addLayout(self.verticalLayout_9)
		self.horizontalLayout_3.addWidget(self.groupBox_6)
		self.verticalLayout_2.addLayout(self.horizontalLayout_3)
		self.verticalLayout_2.setStretch(0, 2)
		self.verticalLayout_2.setStretch(1, 1)
		self.horizontalLayout_2.addLayout(self.verticalLayout_2)
		self.ptabWidget.addTab(self.tabPolygon, _fromUtf8(""))
		self.tabPerson = QWidget()
		self.tabPerson.setObjectName(_fromUtf8("tabPerson"))
		self.horizontalLayout_19 = QHBoxLayout(self.tabPerson)
		self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
		self.verticalLayout_11 = QVBoxLayout()
		self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
		self.verticalLayout_15 = QVBoxLayout()
		self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
		self.horizontalLayout_25 = QHBoxLayout()
		self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
		self.label_4 = QLabel(self.tabPerson)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.horizontalLayout_25.addWidget(self.label_4)
		self.searchPersonLineEdit = QLineEdit(self.tabPerson)
		self.searchPersonLineEdit.setMinimumSize(QtCore.QSize(0, 40))
		self.searchPersonLineEdit.setObjectName(_fromUtf8("searchPersonLineEdit"))
		self.searchPersonLineEdit.setClearButtonEnabled(True)
		self.horizontalLayout_25.addWidget(self.searchPersonLineEdit)
		self.addPersonButton = QPushButton(self.tabPerson)
		self.addPersonButton.setMinimumSize(QtCore.QSize(120, 40))
		self.addPersonButton.setObjectName(_fromUtf8("addPersonButton"))
		self.horizontalLayout_25.addWidget(self.addPersonButton)
		self.delPersonButton = QPushButton(self.tabPerson)
		self.delPersonButton.setMinimumSize(QtCore.QSize(120, 40))
		self.delPersonButton.setObjectName(_fromUtf8("delPersonButton"))
		self.horizontalLayout_25.addWidget(self.delPersonButton)
		self.editPersonButton = QPushButton(self.tabPerson)
		sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.editPersonButton.sizePolicy().hasHeightForWidth())
		self.editPersonButton.setSizePolicy(sizePolicy)
		self.editPersonButton.setMinimumSize(QtCore.QSize(120, 40))
		self.editPersonButton.setObjectName(_fromUtf8("editPersonButton"))
		self.horizontalLayout_25.addWidget(self.editPersonButton)
		spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
		self.horizontalLayout_25.addItem(spacerItem)
		self.verticalLayout_15.addLayout(self.horizontalLayout_25)
		self.personTableView = QTableView(self.tabPerson)
		sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.personTableView.sizePolicy().hasHeightForWidth())
		self.personTableView.setSizePolicy(sizePolicy)
		self.personTableView.setObjectName(_fromUtf8("personTableView"))
		self.verticalLayout_15.addWidget(self.personTableView)
		self.verticalLayout_11.addLayout(self.verticalLayout_15)
		self.horizontalLayout_27 = QGroupBox(self.tabPerson)
		self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
		self.verticalLayout_17 = QVBoxLayout(self.horizontalLayout_27)
		self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
		self.verticalLayout_22 = QVBoxLayout()
		self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
		self.horizontalLayout_32 = QHBoxLayout()
		self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
		self.addMemberButton = QPushButton(self.horizontalLayout_27)
		self.addMemberButton.setMinimumSize(QtCore.QSize(125, 40))
		self.addMemberButton.setObjectName(_fromUtf8("addMemberButton"))
		self.horizontalLayout_32.addWidget(self.addMemberButton)
		self.delMemberButton = QPushButton(self.horizontalLayout_27)
		self.delMemberButton.setMinimumSize(QtCore.QSize(125, 40))
		self.delMemberButton.setObjectName(_fromUtf8("delMemberButton"))
		self.horizontalLayout_32.addWidget(self.delMemberButton)
		self.updateMemberButton = QPushButton(self.horizontalLayout_27)
		self.updateMemberButton.setMinimumSize(QtCore.QSize(125, 40))
		self.updateMemberButton.setObjectName(_fromUtf8("updateMemberButton"))
		self.horizontalLayout_32.addWidget(self.updateMemberButton)
		spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
		self.horizontalLayout_32.addItem(spacerItem1)
		self.verticalLayout_22.addLayout(self.horizontalLayout_32)
		self.memberTableView = QTableView(self.horizontalLayout_27)
		self.memberTableView.setObjectName(_fromUtf8("memberTableView"))
		self.verticalLayout_22.addWidget(self.memberTableView)
		self.horizontalLayout_33 = QHBoxLayout()
		self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
		self.saveTrainingButton = QPushButton(self.horizontalLayout_27)
		self.saveTrainingButton.setMinimumSize(QtCore.QSize(125, 40))
		self.saveTrainingButton.setObjectName(_fromUtf8("saveTrainingButton"))
		self.horizontalLayout_33.addWidget(self.saveTrainingButton)
		self.delTrainingButton = QPushButton(self.horizontalLayout_27)
		self.delTrainingButton.setMinimumSize(QtCore.QSize(125, 40))
		self.delTrainingButton.setObjectName(_fromUtf8("delTrainingButton"))
		self.horizontalLayout_33.addWidget(self.delTrainingButton)
		spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
		self.horizontalLayout_33.addItem(spacerItem2)
		self.verticalLayout_22.addLayout(self.horizontalLayout_33)
		self.verticalLayout_17.addLayout(self.verticalLayout_22)
		self.verticalLayout_11.addWidget(self.horizontalLayout_27)
		self.horizontalLayout_19.addLayout(self.verticalLayout_11)
		self.ptabWidget.addTab(self.tabPerson, _fromUtf8(""))
		self.tabTraining = QWidget()
		self.tabTraining.setObjectName(_fromUtf8("tabTraining"))
		self.horizontalLayout_21 = QHBoxLayout(self.tabTraining)
		self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
		self.verticalLayout_12 = QVBoxLayout()
		self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
		self.verticalLayout_13 = QVBoxLayout()
		self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
		self.horizontalLayout_18 = QHBoxLayout()
		self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
		self.printTrainingButton = QPushButton(self.tabTraining)
		self.printTrainingButton.setObjectName(_fromUtf8("printTrainingButton"))
		self.horizontalLayout_18.addWidget(self.printTrainingButton)
		spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
		self.horizontalLayout_18.addItem(spacerItem3)
		self.verticalLayout_13.addLayout(self.horizontalLayout_18)
		self.trainingTableView = QTableView(self.tabTraining)
		self.trainingTableView.setObjectName(_fromUtf8("trainingTableView"))
		self.verticalLayout_13.addWidget(self.trainingTableView)
		self.verticalLayout_12.addLayout(self.verticalLayout_13)
		self.horizontalLayout_21.addLayout(self.verticalLayout_12)
		self.ptabWidget.addTab(self.tabTraining, _fromUtf8(""))
		self.verticalLayout.addWidget(self.ptabWidget)
		self.horizontalLayout.addLayout(self.verticalLayout)
		MainWindow.setCentralWidget(self.centralwidget)
		#self.menubar = QMenuBar(MainWindow)
		#self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 29))
		#self.menubar.setObjectName(_fromUtf8("menubar"))
		#self.menuMenu = QMenu(self.menubar)
		#self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
		#MainWindow.setMenuBar(self.menubar)
		self.statusbar = QStatusBar(MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		MainWindow.setStatusBar(self.statusbar)
		self.actionItem_1 = QAction(MainWindow)
		self.actionItem_1.setObjectName(_fromUtf8("actionItem_1"))
		self.actionItem_2 = QAction(MainWindow)
		self.actionItem_2.setObjectName(_fromUtf8("actionItem_2"))
		self.actionItem_3 = QAction(MainWindow)
		self.actionItem_3.setObjectName(_fromUtf8("actionItem_3"))
		self.actionO_aplikaci = QAction(MainWindow)
		self.actionO_aplikaci.setObjectName(_fromUtf8("actionO_aplikaci"))
		#self.menuMenu.addAction(self.actionItem_1)
		#self.menuMenu.addAction(self.actionItem_2)
		#self.menuMenu.addAction(self.actionItem_3)
		#self.menuMenu.addSeparator()
		#self.menuMenu.addAction(self.actionO_aplikaci)
		#self.menubar.addAction(self.menuMenu.menuAction())

		self.retranslateUi(MainWindow)
		self.ptabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(_translate("MainWindow", "Polygon Teplice", None))
		self.floor_02.setText(_translate("MainWindow", "2", None))
		self.floor_03.setText(_translate("MainWindow", "3", None))
		self.floor_04.setText(_translate("MainWindow", "4", None))
		self.floor_05.setText(_translate("MainWindow", "5", None))
		self.floor_06.setText(_translate("MainWindow", "6", None))
		self.floor_07.setText(_translate("MainWindow", "7", None))
		self.floor_08.setText(_translate("MainWindow", "8", None))
		self.floor_09.setText(_translate("MainWindow", "9", None))
		self.floor_10.setText(_translate("MainWindow", "10", None))
		self.floor_11.setText(_translate("MainWindow", "11", None))
		self.floor_12.setText(_translate("MainWindow", "12", None))
		self.floor_13.setText(_translate("MainWindow", "13", None))
		self.floor_14.setText(_translate("MainWindow", "14", None))
		self.floor_15.setText(_translate("MainWindow", "15", None))
		self.floor_16.setText(_translate("MainWindow", "16", None))
		self.floor_17.setText(_translate("MainWindow", "17", None))
		self.floor_18.setText(_translate("MainWindow", "18", None))
		self.floor_19.setText(_translate("MainWindow", "19", None))
		self.floor_20.setText(_translate("MainWindow", "20", None))
		self.floor_01.setText(_translate("MainWindow", "1", None))
		self.floor_21.setText(_translate("MainWindow", "21", None))
		self.floor_22.setText(_translate("MainWindow", "22", None))
		self.floor_23.setText(_translate("MainWindow", "23", None))
		self.floor_24.setText(_translate("MainWindow", "24", None))
		self.floor_25.setText(_translate("MainWindow", "25", None))
		self.floor_26.setText(_translate("MainWindow", "26", None))
		self.floor_27.setText(_translate("MainWindow", "27", None))
		self.floor_28.setText(_translate("MainWindow", "28", None))
		self.floor_29.setText(_translate("MainWindow", "29", None))
		self.floor_30.setText(_translate("MainWindow", "30", None))
		self.floor_31.setText(_translate("MainWindow", "31", None))
		self.floor_32.setText(_translate("MainWindow", "32", None))
		self.floor_33.setText(_translate("MainWindow", "33", None))
		self.floor_34.setText(_translate("MainWindow", "34", None))
		self.floor_36.setText(_translate("MainWindow", "36", None))
		self.floor_37.setText(_translate("MainWindow", "37", None))
		self.floor_38.setText(_translate("MainWindow", "38", None))
		self.floor_39.setText(_translate("MainWindow", "39", None))
		self.floor_40.setText(_translate("MainWindow", "40", None))
		self.floor_41.setText(_translate("MainWindow", "41", None))
		self.floor_42.setText(_translate("MainWindow", "42", None))
		self.roura.setText(_translate("MainWindow", "Roura", None))
		self.floor_43.setText(_translate("MainWindow", "43", None))
		self.floor_44.setText(_translate("MainWindow", "44", None))
		self.floor_45.setText(_translate("MainWindow", "45", None))
		self.floor_46.setText(_translate("MainWindow", "46", None))
		self.floor_47.setText(_translate("MainWindow", "47", None))
		self.floor_48.setText(_translate("MainWindow", "48", None))
		self.floor_49.setText(_translate("MainWindow", "49", None))
		self.floor_50.setText(_translate("MainWindow", "50", None))
		self.floor_51.setText(_translate("MainWindow", "51", None))
		self.floor_52.setText(_translate("MainWindow", "52", None))
		self.floor_53.setText(_translate("MainWindow", "53", None))
		self.floor_54.setText(_translate("MainWindow", "54", None))
		self.floor_55.setText(_translate("MainWindow", "55", None))
		self.floor_56.setText(_translate("MainWindow", "56", None))
		self.floor_57.setText(_translate("MainWindow", "57", None))
		self.floor_58.setText(_translate("MainWindow", "58", None))
		self.floor_59.setText(_translate("MainWindow", "59", None))
		self.floor_35.setText(_translate("MainWindow", "35", None))
		self.groupBox_4.setTitle(_translate("MainWindow", "Technologie", None))
		self.fan12Button.setText(_translate("MainWindow", "Ventilátor 1,2", None))
		self.fan34Button.setText(_translate("MainWindow", "Ventilátor 3,4", None))
		self.fanControlRoomButton.setText(_translate("MainWindow", "Ventilátor VELÍN", None))
		self.glowButton.setText(_translate("MainWindow", "Žhavení zadýmení", None))
		self.stroboButton.setText(_translate("MainWindow", "Záblesky", None))
		self.hotZoneButton.setText(_translate("MainWindow", "Teplá zóna", None))
		self.louverButton.setText(_translate("MainWindow", "Žaluzie", None))
		self.smokeButton.setText(_translate("MainWindow", "Zadýmení", None))
		self.groupBox_3.setTitle(_translate("MainWindow", "Světla", None))
		self.polygonLight1Button.setText(_translate("MainWindow", "Světla Polygon", None))
		self.polygonLight2Button.setText(_translate("MainWindow", "Světla Polygon", None))
		self.polygonLight3Button.setText(_translate("MainWindow", "Světla Polygon", None))
		self.hotZoneLightButton.setText(_translate("MainWindow", "Světla Teplá zóna", None))
		self.stressRoomLightButton.setText(_translate("MainWindow", "Zátěžová míst.", None))
		self.infraLightButton.setText(_translate("MainWindow", "Infra osvětlení", None))
		self.controlRoomLightButton.setText(_translate("MainWindow", "Světla VELÍN", None))
		self.helpLightButton.setText(_translate("MainWindow", "Pomocná světla", None))
		self.groupBox.setTitle(_translate("MainWindow", "Zvuky", None))
		self.pushButton_19.setText(_translate("MainWindow", "Zvukové efekty", None))
		self.groupBox_6.setTitle(_translate("MainWindow", "Obsluha", None))
		self.emergencyButton.setText(_translate("MainWindow", "Nouzové tlačítko", None))
		self.startButton.setText(_translate("MainWindow", "Start", None))
		self.stopButton.setText(_translate("MainWindow", "Stop", None))
		self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabPolygon), _translate("MainWindow", "Polygon", None))
		self.label_4.setText(_translate("MainWindow", "Vyhledat osobu", None))
		self.addPersonButton.setText(_translate("MainWindow", "Založit osobu", None))
		self.delPersonButton.setText(_translate("MainWindow", "Smazat osobu", None))
		self.editPersonButton.setText(_translate("MainWindow", "Upravit osobu", None))
		self.horizontalLayout_27.setTitle(_translate("MainWindow", "Cvičící osoby", None))
		self.addMemberButton.setText(_translate("MainWindow", "Přidat cvičence", None))
		self.delMemberButton.setText(_translate("MainWindow", "Smazat cvičence", None))
		self.updateMemberButton.setText(_translate("MainWindow", "Upravit hodnoty", None))
		self.saveTrainingButton.setText(_translate("MainWindow", "Uložit cvičení", None))
		self.delTrainingButton.setText(_translate("MainWindow", "Smazat cvičení", None))
		self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabPerson), _translate("MainWindow", "Osoby", None))
		self.printTrainingButton.setText(_translate("MainWindow", "Tisk protokolu", None))
		self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabTraining), _translate("MainWindow", "Cvičení", None))
		#self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
		self.actionItem_1.setText(_translate("MainWindow", "Item 1", None))
		self.actionItem_2.setText(_translate("MainWindow", "Item 2", None))
		self.actionItem_3.setText(_translate("MainWindow", "Item 3", None))
		self.actionO_aplikaci.setText(_translate("MainWindow", "O aplikaci", None))


class PersonForm(QDialog):
	def __init__(self, model, row = None):
		QDialog.__init__(self)
		self.row = row
		self.model = model
		self.setupUi(self)

	def setupUi(self, Dialog):
		Dialog.setObjectName(_fromUtf8("Dialog"))
		Dialog.resize(500, 360)
		self.verticalLayoutWidget = QWidget(Dialog)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 441, 291))
		self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
		self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.formLayout = QFormLayout()
		self.formLayout.setObjectName(_fromUtf8("formLayout"))
		self.verticalLayout_5 = QVBoxLayout()
		self.verticalLayout_5.setSpacing(10)
		self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
		self.nameLineEdit = QLineEdit(self.verticalLayoutWidget)
		self.nameLineEdit.setMinimumSize(QtCore.QSize(0, 25))
		self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
		self.verticalLayout_5.addWidget(self.nameLineEdit)
		self.surnameLineEdit = QLineEdit(self.verticalLayoutWidget)
		self.surnameLineEdit.setMinimumSize(QtCore.QSize(0, 25))
		self.surnameLineEdit.setObjectName(_fromUtf8("surnameLineEdit"))
		self.verticalLayout_5.addWidget(self.surnameLineEdit)
		self.birthdayDateEdit = QDateEdit(self.verticalLayoutWidget)
		self.birthdayDateEdit.setMinimumSize(QtCore.QSize(0, 25))
		self.birthdayDateEdit.setCalendarPopup(True)
		self.birthdayDateEdit.setObjectName(_fromUtf8("birthdayDateEdit"))
		self.verticalLayout_5.addWidget(self.birthdayDateEdit)
		self.oecLineEdit = QLineEdit(self.verticalLayoutWidget)
		self.oecLineEdit.setMinimumSize(QtCore.QSize(0, 25))
		self.oecLineEdit.setObjectName(_fromUtf8("oecLineEdit"))
		self.verticalLayout_5.addWidget(self.oecLineEdit)
		self.unitLineEdit = QLineEdit(self.verticalLayoutWidget)
		self.unitLineEdit.setMinimumSize(QtCore.QSize(0, 25))
		self.unitLineEdit.setText(_fromUtf8(""))
		self.unitLineEdit.setObjectName(_fromUtf8("unitLineEdit"))
		self.verticalLayout_5.addWidget(self.unitLineEdit)
		self.formLayout.setLayout(0, QFormLayout.FieldRole, self.verticalLayout_5)
		self.verticalLayout_4 = QVBoxLayout()
		self.verticalLayout_4.setSpacing(10)
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.label = QLabel(self.verticalLayoutWidget)
		self.label.setMinimumSize(QtCore.QSize(0, 25))
		self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label.setObjectName(_fromUtf8("label"))
		self.verticalLayout_4.addWidget(self.label)
		self.label_2 = QLabel(self.verticalLayoutWidget)
		self.label_2.setMinimumSize(QtCore.QSize(0, 25))
		self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.verticalLayout_4.addWidget(self.label_2)
		self.label_3 = QLabel(self.verticalLayoutWidget)
		self.label_3.setMinimumSize(QtCore.QSize(0, 25))
		self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.verticalLayout_4.addWidget(self.label_3)
		self.label_4 = QLabel(self.verticalLayoutWidget)
		self.label_4.setMinimumSize(QtCore.QSize(0, 25))
		self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.verticalLayout_4.addWidget(self.label_4)
		self.label_5 = QLabel(self.verticalLayoutWidget)
		self.label_5.setMinimumSize(QtCore.QSize(0, 25))
		self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.verticalLayout_4.addWidget(self.label_5)
		self.formLayout.setLayout(0, QFormLayout.LabelRole, self.verticalLayout_4)
		self.horizontalLayout = QHBoxLayout()
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.formLayout.setLayout(1, QFormLayout.LabelRole, self.horizontalLayout)
		self.verticalLayout_2 = QVBoxLayout()
		self.verticalLayout_2.setObjectName(u"verticalLayout_2")
		self.addMemberCheckBox = QCheckBox(self.verticalLayoutWidget)
		self.addMemberCheckBox.setObjectName(u"addMemberCheckBox")
		self.addMemberCheckBox.setEnabled(True)
		self.addMemberCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
		self.addMemberCheckBox.setChecked(True)
		self.verticalLayout_2.addWidget(self.addMemberCheckBox)
		self.formLayout.setLayout(1, QFormLayout.SpanningRole, self.verticalLayout_2)

		self.buttonBox = QDialogButtonBox(self.verticalLayoutWidget)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Save)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.formLayout.setWidget(2, QFormLayout.FieldRole, self.buttonBox)
		self.verticalLayout.addLayout(self.formLayout)
		self.verticalLayoutWidget.raise_()

		self.birthdayDateEdit.setDisplayFormat("dd.MM.yyyy")
		self.oecLineEdit.setText("")
		self.unitLineEdit.setText("")
		self.mapper = QDataWidgetMapper(self)
		self.mapper.setSubmitPolicy(QDataWidgetMapper.ManualSubmit)
		self.mapper.setModel(self.model)
		self.mapper.addMapping(self.nameLineEdit,1)
		self.mapper.addMapping(self.surnameLineEdit,2)
		self.mapper.addMapping(self.birthdayDateEdit,3)
		self.mapper.addMapping(self.oecLineEdit,4)
		self.mapper.addMapping(self.unitLineEdit,5)
		self.addMember = False

		if self.row is None:
			self.row = self.model.rowCount()
			self.mapper.submit()
			self.model.insertRow(self.row)
			#self.mapper.setCurrentIndex(self.row)
			self.buttonBox.accepted.connect(self.addPerson)
		else:
			self.addMemberCheckBox.setEnabled(False)
			name = self.model.record(self.row).value("name")
			surname = self.model.record(self.row).value("surname")
			birthday = self.model.record(self.row).value("birthday")
			oec = self.model.record(self.row).value("oec")
			unit = self.model.record(self.row).value("unit")
			self.label.setText(name)
			self.nameLineEdit.setText(name)
			self.surnameLineEdit.setText(surname)
			self.birthdayDateEdit.setDate(birthday)
			self.oecLineEdit.setText(oec)
			self.unitLineEdit.setText(unit)
			self.buttonBox.accepted.connect(self.editPerson)

		self.retranslateUi(Dialog)
		self.buttonBox.rejected.connect(self.reject)

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "Osoba", None))
		self.label.setText(_translate("Dialog", "Jméno", None))
		self.label_2.setText(_translate("Dialog", "Příjmení", None))
		self.label_3.setText(_translate("Dialog", "Datum narození", None))
		self.label_4.setText(_translate("Dialog", "OEČ", None))
		self.label_5.setText(_translate("Dialog", "Organizace", None))
		self.addMemberCheckBox.setText(_translate("Dialog", u"Přidat do cvičení", None))

	def addPerson(self):
		self.mapper.submit()
		#self.mapper.setCurrentIndex(self.row)
		self.model.submitAll()
		self.model.select()
		if self.addMemberCheckBox.isChecked():
			self.addMember = True
		self.accept()

	def editPerson(self):
		query = self.model.query()
		idperson = self.model.record(self.row).value("idPerson")
		name = self.nameLineEdit.text()
		surname = self.surnameLineEdit.text()
		birthday = QtCore.QDateTime.fromString(self.birthdayDateEdit.text(), "dd.MM.yyyy").toString("yyyy-MM-dd")
		oec = self.oecLineEdit.text()
		unit = self.unitLineEdit.text()
		query.exec_("UPDATE person SET name = '%s', surname = '%s', birthday = '%s', oec = '%s', unit = '%s' WHERE idPerson=%d" % (name, surname, birthday, oec, unit, idperson))
		self.model.select()
		self.accept()

class MemberForm(QDialog):
	def __init__(self, model, row):
		QDialog.__init__(self)
		#super(PersonForm, self).__init__(parent)
		self.model = model
		self.row = row
		self.setupUi(self)

	def setupUi(self, MemberForm):
		MemberForm.setObjectName(_fromUtf8("Dialog"))
		MemberForm.resize(404, 341)
		self.buttonBox = QDialogButtonBox(MemberForm)
		self.buttonBox.setGeometry(QtCore.QRect(40, 280, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.label = QLabel(MemberForm)
		self.label.setGeometry(QtCore.QRect(20, 20, 300, 45))
		font = QtGui.QFont()
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setText(_fromUtf8(""))
		self.label.setObjectName(_fromUtf8("label"))
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label_2 = QLabel(MemberForm)
		self.label_2.setGeometry(QtCore.QRect(20, 80, 150, 30))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.label_3 = QLabel(MemberForm)
		self.label_3.setGeometry(QtCore.QRect(20, 130, 150, 30))
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.label_4 = QLabel(MemberForm)
		self.label_4.setGeometry(QtCore.QRect(20, 180, 150, 30))
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.validator = QtGui.QIntValidator(0,999,self)
		self.comboBox_volume = QComboBox(MemberForm)
		self.comboBox_volume.setGeometry(QtCore.QRect(180, 80, 130, 30))
		self.comboBox_volume.setObjectName(_fromUtf8("comboBox_volume"))
		self.comboBox_volume.addItems(["6.0","7.0","6.8"])
		self.comboBox_volume.currentIndexChanged.connect(self.selectionchange)
		self.lineEdit_3 = QLineEdit(MemberForm)
		self.lineEdit_3.setValidator(self.validator)
		self.lineEdit_3.setGeometry(QtCore.QRect(180, 130, 130, 30))
		self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
		self.lineEdit_4 = QLineEdit(MemberForm)
		self.lineEdit_4.setValidator(self.validator)
		self.lineEdit_4.setGeometry(QtCore.QRect(180, 180, 130, 30))
		self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))

		if self.row < 0:self.row=0
		name = self.model.record(self.row).value("name")
		volume = self.model.record(self.row).value("volume")
		press_start = self.model.record(self.row).value("press_start")
		press_end = self.model.record(self.row).value("press_end")
		self.label.setText(name)
		self.comboBox_volume.setCurrentIndex(self.comboBox_volume.findText(str(volume)))
		self.lineEdit_3.setText(str(press_start))
		self.lineEdit_4.setText(str(press_end))

		self.retranslateUi(MemberForm)
		self.buttonBox.rejected.connect(self.reject)
		self.buttonBox.accepted.connect(self.updateMember)

	def selectionchange(self):
		value = self.comboBox_volume.currentIndex()
		if value == 0:
			self.lineEdit_3.setText("300")
		elif value == 1:
			self.lineEdit_3.setText("300")
		elif value == 2:
			self.lineEdit_3.setText("200")

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "Hodnoty", None))
		self.label_2.setText(_translate("Dialog", "Objem láhve (L)", None))
		self.label_3.setText(_translate("Dialog", "Tlak na začátku (Bar)", None))
		self.label_4.setText(_translate("Dialog", "Tlak na konci (Bar)", None))

	def updateMember(self):
		query = self.model.query()
		idmember = self.model.record(self.row).value("idMember")
		volume = self.comboBox_volume.currentText()
		press_start =  self.lineEdit_3.text()
		press_end =  self.lineEdit_4.text()
		query.exec_("UPDATE member SET volume=%s, press_start=%s, press_end=%s WHERE idMember=%d" % (volume,press_start,press_end,idmember))
		self.model.view()
		self.accept()
