# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowPolygon.ui'
#
# Created: Wed Nov 11 09:55:26 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1248, 895)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ptabWidget = QtGui.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 54, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 244, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 174, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 128, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 140, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 240, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.ptabWidget.setPalette(palette)
        self.ptabWidget.setObjectName(_fromUtf8("ptabWidget"))
        self.tabPolygon = QtGui.QWidget()
        self.tabPolygon.setObjectName(_fromUtf8("tabPolygon"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabPolygon)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_5 = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.floor_02 = QtGui.QLabel(self.groupBox_5)
        self.floor_02.setGeometry(QtCore.QRect(220, 220, 60, 60))
        self.floor_02.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_02.setTextFormat(QtCore.Qt.PlainText)
        self.floor_02.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_02.setObjectName(_fromUtf8("floor_02"))
        self.floor_03 = QtGui.QLabel(self.groupBox_5)
        self.floor_03.setGeometry(QtCore.QRect(160, 220, 60, 60))
        self.floor_03.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_03.setTextFormat(QtCore.Qt.PlainText)
        self.floor_03.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_03.setObjectName(_fromUtf8("floor_03"))
        self.floor_04 = QtGui.QLabel(self.groupBox_5)
        self.floor_04.setGeometry(QtCore.QRect(160, 280, 60, 60))
        self.floor_04.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_04.setTextFormat(QtCore.Qt.PlainText)
        self.floor_04.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_04.setObjectName(_fromUtf8("floor_04"))
        self.floor_05 = QtGui.QLabel(self.groupBox_5)
        self.floor_05.setGeometry(QtCore.QRect(100, 280, 60, 60))
        self.floor_05.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_05.setTextFormat(QtCore.Qt.PlainText)
        self.floor_05.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_05.setObjectName(_fromUtf8("floor_05"))
        self.floor_06 = QtGui.QLabel(self.groupBox_5)
        self.floor_06.setGeometry(QtCore.QRect(40, 280, 60, 60))
        self.floor_06.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_06.setTextFormat(QtCore.Qt.PlainText)
        self.floor_06.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_06.setObjectName(_fromUtf8("floor_06"))
        self.floor_07 = QtGui.QLabel(self.groupBox_5)
        self.floor_07.setGeometry(QtCore.QRect(40, 220, 60, 60))
        self.floor_07.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_07.setTextFormat(QtCore.Qt.PlainText)
        self.floor_07.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_07.setObjectName(_fromUtf8("floor_07"))
        self.floor_08 = QtGui.QLabel(self.groupBox_5)
        self.floor_08.setGeometry(QtCore.QRect(100, 220, 60, 60))
        self.floor_08.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_08.setTextFormat(QtCore.Qt.PlainText)
        self.floor_08.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_08.setObjectName(_fromUtf8("floor_08"))
        self.floor_09 = QtGui.QLabel(self.groupBox_5)
        self.floor_09.setGeometry(QtCore.QRect(100, 160, 60, 60))
        self.floor_09.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_09.setTextFormat(QtCore.Qt.PlainText)
        self.floor_09.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_09.setObjectName(_fromUtf8("floor_09"))
        self.floor_10 = QtGui.QLabel(self.groupBox_5)
        self.floor_10.setGeometry(QtCore.QRect(40, 160, 60, 60))
        self.floor_10.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_10.setTextFormat(QtCore.Qt.PlainText)
        self.floor_10.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_10.setObjectName(_fromUtf8("floor_10"))
        self.floor_11 = QtGui.QLabel(self.groupBox_5)
        self.floor_11.setGeometry(QtCore.QRect(40, 100, 60, 60))
        self.floor_11.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_11.setTextFormat(QtCore.Qt.PlainText)
        self.floor_11.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_11.setObjectName(_fromUtf8("floor_11"))
        self.floor_12 = QtGui.QLabel(self.groupBox_5)
        self.floor_12.setGeometry(QtCore.QRect(40, 40, 60, 60))
        self.floor_12.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_12.setTextFormat(QtCore.Qt.PlainText)
        self.floor_12.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_12.setObjectName(_fromUtf8("floor_12"))
        self.floor_13 = QtGui.QLabel(self.groupBox_5)
        self.floor_13.setGeometry(QtCore.QRect(100, 40, 60, 60))
        self.floor_13.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_13.setTextFormat(QtCore.Qt.PlainText)
        self.floor_13.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_13.setObjectName(_fromUtf8("floor_13"))
        self.floor_14 = QtGui.QLabel(self.groupBox_5)
        self.floor_14.setGeometry(QtCore.QRect(100, 100, 60, 60))
        self.floor_14.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_14.setTextFormat(QtCore.Qt.PlainText)
        self.floor_14.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_14.setObjectName(_fromUtf8("floor_14"))
        self.floor_15 = QtGui.QLabel(self.groupBox_5)
        self.floor_15.setGeometry(QtCore.QRect(160, 100, 60, 60))
        self.floor_15.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_15.setTextFormat(QtCore.Qt.PlainText)
        self.floor_15.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_15.setObjectName(_fromUtf8("floor_15"))
        self.floor_16 = QtGui.QLabel(self.groupBox_5)
        self.floor_16.setGeometry(QtCore.QRect(160, 40, 60, 60))
        self.floor_16.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_16.setTextFormat(QtCore.Qt.PlainText)
        self.floor_16.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_16.setObjectName(_fromUtf8("floor_16"))
        self.floor_17 = QtGui.QLabel(self.groupBox_5)
        self.floor_17.setGeometry(QtCore.QRect(220, 40, 60, 60))
        self.floor_17.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_17.setTextFormat(QtCore.Qt.PlainText)
        self.floor_17.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_17.setObjectName(_fromUtf8("floor_17"))
        self.floor_18 = QtGui.QLabel(self.groupBox_5)
        self.floor_18.setGeometry(QtCore.QRect(220, 100, 60, 60))
        self.floor_18.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_18.setTextFormat(QtCore.Qt.PlainText)
        self.floor_18.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_18.setObjectName(_fromUtf8("floor_18"))
        self.floor_19 = QtGui.QLabel(self.groupBox_5)
        self.floor_19.setGeometry(QtCore.QRect(280, 100, 60, 60))
        self.floor_19.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_19.setTextFormat(QtCore.Qt.PlainText)
        self.floor_19.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_19.setObjectName(_fromUtf8("floor_19"))
        self.floor_20 = QtGui.QLabel(self.groupBox_5)
        self.floor_20.setGeometry(QtCore.QRect(340, 100, 60, 60))
        self.floor_20.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_20.setTextFormat(QtCore.Qt.PlainText)
        self.floor_20.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_20.setObjectName(_fromUtf8("floor_20"))
        self.floor_01 = QtGui.QLabel(self.groupBox_5)
        self.floor_01.setGeometry(QtCore.QRect(220, 280, 60, 60))
        self.floor_01.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_01.setTextFormat(QtCore.Qt.PlainText)
        self.floor_01.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_01.setObjectName(_fromUtf8("floor_01"))
        self.floor_21 = QtGui.QLabel(self.groupBox_5)
        self.floor_21.setGeometry(QtCore.QRect(340, 160, 60, 60))
        self.floor_21.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_21.setTextFormat(QtCore.Qt.PlainText)
        self.floor_21.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_21.setObjectName(_fromUtf8("floor_21"))
        self.floor_22 = QtGui.QLabel(self.groupBox_5)
        self.floor_22.setGeometry(QtCore.QRect(340, 220, 60, 60))
        self.floor_22.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_22.setTextFormat(QtCore.Qt.PlainText)
        self.floor_22.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_22.setObjectName(_fromUtf8("floor_22"))
        self.floor_23 = QtGui.QLabel(self.groupBox_5)
        self.floor_23.setGeometry(QtCore.QRect(400, 220, 60, 60))
        self.floor_23.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_23.setTextFormat(QtCore.Qt.PlainText)
        self.floor_23.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_23.setObjectName(_fromUtf8("floor_23"))
        self.floor_24 = QtGui.QLabel(self.groupBox_5)
        self.floor_24.setGeometry(QtCore.QRect(400, 160, 60, 60))
        self.floor_24.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_24.setTextFormat(QtCore.Qt.PlainText)
        self.floor_24.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_24.setObjectName(_fromUtf8("floor_24"))
        self.floor_25 = QtGui.QLabel(self.groupBox_5)
        self.floor_25.setGeometry(QtCore.QRect(400, 100, 60, 60))
        self.floor_25.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_25.setTextFormat(QtCore.Qt.PlainText)
        self.floor_25.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_25.setObjectName(_fromUtf8("floor_25"))
        self.floor_26 = QtGui.QLabel(self.groupBox_5)
        self.floor_26.setGeometry(QtCore.QRect(460, 100, 60, 60))
        self.floor_26.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_26.setTextFormat(QtCore.Qt.PlainText)
        self.floor_26.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_26.setObjectName(_fromUtf8("floor_26"))
        self.floor_27 = QtGui.QLabel(self.groupBox_5)
        self.floor_27.setGeometry(QtCore.QRect(520, 100, 60, 60))
        self.floor_27.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_27.setTextFormat(QtCore.Qt.PlainText)
        self.floor_27.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_27.setObjectName(_fromUtf8("floor_27"))
        self.floor_28 = QtGui.QLabel(self.groupBox_5)
        self.floor_28.setGeometry(QtCore.QRect(580, 100, 60, 60))
        self.floor_28.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_28.setTextFormat(QtCore.Qt.PlainText)
        self.floor_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_28.setObjectName(_fromUtf8("floor_28"))
        self.floor_29 = QtGui.QLabel(self.groupBox_5)
        self.floor_29.setGeometry(QtCore.QRect(580, 40, 60, 60))
        self.floor_29.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_29.setTextFormat(QtCore.Qt.PlainText)
        self.floor_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_29.setObjectName(_fromUtf8("floor_29"))
        self.floor_30 = QtGui.QLabel(self.groupBox_5)
        self.floor_30.setGeometry(QtCore.QRect(520, 40, 60, 60))
        self.floor_30.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_30.setTextFormat(QtCore.Qt.PlainText)
        self.floor_30.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_30.setObjectName(_fromUtf8("floor_30"))
       
        self.floor_35 = QtGui.QLabel(self.groupBox_5)
        self.floor_35.setGeometry(QtCore.QRect(700, 40, 60, 60))
        self.floor_35.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_35.setTextFormat(QtCore.Qt.PlainText)
        self.floor_35.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_35.setObjectName(_fromUtf8("floor_35"))
        self.floor_36 = QtGui.QLabel(self.groupBox_5)
        self.floor_36.setGeometry(QtCore.QRect(640, 40, 60, 60))
        self.floor_36.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_36.setTextFormat(QtCore.Qt.PlainText)
        self.floor_36.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.floor_36.setObjectName(_fromUtf8("floor_36"))
        self.floor_37 = QtGui.QLabel(self.groupBox_5)
        self.floor_37.setGeometry(QtCore.QRect(640, 100, 60, 60))
        self.floor_37.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_37.setTextFormat(QtCore.Qt.PlainText)
        self.floor_37.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.floor_37.setObjectName(_fromUtf8("floor_37"))
        self.floor_38 = QtGui.QLabel(self.groupBox_5)
        self.floor_38.setGeometry(QtCore.QRect(640, 160, 60, 60))
        self.floor_38.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_38.setTextFormat(QtCore.Qt.PlainText)
        self.floor_38.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_38.setObjectName(_fromUtf8("floor_38"))
        self.floor_41 = QtGui.QLabel(self.groupBox_5)
        self.floor_41.setGeometry(QtCore.QRect(700, 160, 60, 60))
        self.floor_41.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_41.setTextFormat(QtCore.Qt.PlainText)
        self.floor_41.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_41.setObjectName(_fromUtf8("floor_41"))
        self.floor_42 = QtGui.QLabel(self.groupBox_5)
        self.floor_42.setGeometry(QtCore.QRect(700, 220, 60, 60))
        self.floor_42.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_42.setTextFormat(QtCore.Qt.PlainText)
        self.floor_42.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.floor_42.setObjectName(_fromUtf8("floor_42"))
        self.floor_43 = QtGui.QLabel(self.groupBox_5)
        self.floor_43.setGeometry(QtCore.QRect(700, 280, 60, 60))
        self.floor_43.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_43.setTextFormat(QtCore.Qt.PlainText)
        self.floor_43.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_43.setObjectName(_fromUtf8("floor_43"))
        self.floor_44 = QtGui.QLabel(self.groupBox_5)
        self.floor_44.setGeometry(QtCore.QRect(640, 280, 60, 60))
        self.floor_44.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_44.setTextFormat(QtCore.Qt.PlainText)
        self.floor_44.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_44.setObjectName(_fromUtf8("floor_44"))
        self.floor_45 = QtGui.QLabel(self.groupBox_5)
        self.floor_45.setGeometry(QtCore.QRect(640, 220, 60, 60))
        self.floor_45.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_45.setTextFormat(QtCore.Qt.PlainText)
        self.floor_45.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.floor_45.setObjectName(_fromUtf8("floor_45"))
        self.floor_46 = QtGui.QLabel(self.groupBox_5)
        self.floor_46.setGeometry(QtCore.QRect(950, 40, 60, 60))
        self.floor_46.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_46.setTextFormat(QtCore.Qt.PlainText)
        self.floor_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_46.setObjectName(_fromUtf8("floor_46"))
        self.floor_47 = QtGui.QLabel(self.groupBox_5)
        self.floor_47.setGeometry(QtCore.QRect(950, 100, 60, 60))
        self.floor_47.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_47.setTextFormat(QtCore.Qt.PlainText)
        self.floor_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_47.setObjectName(_fromUtf8("floor_47"))
        self.floor_48 = QtGui.QLabel(self.groupBox_5)
        self.floor_48.setGeometry(QtCore.QRect(950, 160, 60, 60))
        self.floor_48.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_48.setTextFormat(QtCore.Qt.PlainText)
        self.floor_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_48.setObjectName(_fromUtf8("floor_48"))
        self.floor_49 = QtGui.QLabel(self.groupBox_5)
        self.floor_49.setGeometry(QtCore.QRect(950, 220, 60, 60))
        self.floor_49.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_49.setTextFormat(QtCore.Qt.PlainText)
        self.floor_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_49.setObjectName(_fromUtf8("floor_49"))
        self.floor_50 = QtGui.QLabel(self.groupBox_5)
        self.floor_50.setGeometry(QtCore.QRect(950, 280, 60, 60))
        self.floor_50.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_50.setTextFormat(QtCore.Qt.PlainText)
        self.floor_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_50.setObjectName(_fromUtf8("floor_50"))
        self.floor_51 = QtGui.QLabel(self.groupBox_5)
        self.floor_51.setGeometry(QtCore.QRect(890, 280, 60, 60))
        self.floor_51.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_51.setTextFormat(QtCore.Qt.PlainText)
        self.floor_51.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_51.setObjectName(_fromUtf8("floor_51"))
        self.floor_52 = QtGui.QLabel(self.groupBox_5)
        self.floor_52.setGeometry(QtCore.QRect(980, 270, 60, 60))
        self.floor_52.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_52.setTextFormat(QtCore.Qt.PlainText)
        self.floor_52.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_52.setObjectName(_fromUtf8("floor_52"))
        self.floor_53 = QtGui.QLabel(self.groupBox_5)
        self.floor_53.setGeometry(QtCore.QRect(980, 210, 60, 60))
        self.floor_53.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_53.setTextFormat(QtCore.Qt.PlainText)
        self.floor_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_53.setObjectName(_fromUtf8("floor_53"))
        self.floor_54 = QtGui.QLabel(self.groupBox_5)
        self.floor_54.setGeometry(QtCore.QRect(980, 150, 60, 60))
        self.floor_54.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_54.setTextFormat(QtCore.Qt.PlainText)
        self.floor_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_54.setObjectName(_fromUtf8("floor_54"))
        self.floor_55 = QtGui.QLabel(self.groupBox_5)
        self.floor_55.setGeometry(QtCore.QRect(980, 90, 60, 60))
        self.floor_55.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_55.setTextFormat(QtCore.Qt.PlainText)
        self.floor_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_55.setObjectName(_fromUtf8("floor_55"))
        self.floor_56 = QtGui.QLabel(self.groupBox_5)
        self.floor_56.setGeometry(QtCore.QRect(980, 30, 60, 60))
        self.floor_56.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_56.setTextFormat(QtCore.Qt.PlainText)
        self.floor_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.floor_56.setObjectName(_fromUtf8("floor_56"))
        self.floor_57 = QtGui.QLabel(self.groupBox_5)
        self.floor_57.setGeometry(QtCore.QRect(1010, 20, 60, 60))
        self.floor_57.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_57.setTextFormat(QtCore.Qt.PlainText)
        self.floor_57.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_57.setObjectName(_fromUtf8("floor_57"))
        self.floor_58 = QtGui.QLabel(self.groupBox_5)
        self.floor_58.setGeometry(QtCore.QRect(1010, 80, 60, 60))
        self.floor_58.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_58.setTextFormat(QtCore.Qt.PlainText)
        self.floor_58.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_58.setObjectName(_fromUtf8("floor_58"))
        self.floor_59 = QtGui.QLabel(self.groupBox_5)
        self.floor_59.setGeometry(QtCore.QRect(1010, 140, 60, 60))
        self.floor_59.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_59.setTextFormat(QtCore.Qt.PlainText)
        self.floor_59.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_59.setObjectName(_fromUtf8("floor_59"))
        self.floor_60 = QtGui.QLabel(self.groupBox_5)
        self.floor_60.setGeometry(QtCore.QRect(1010, 200, 60, 60))
        self.floor_60.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_60.setTextFormat(QtCore.Qt.PlainText)
        self.floor_60.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_60.setObjectName(_fromUtf8("floor_60"))
        self.floor_31 = QtGui.QLabel(self.groupBox_5)
        self.floor_31.setGeometry(QtCore.QRect(600, 20, 60, 60))
        self.floor_31.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_31.setTextFormat(QtCore.Qt.PlainText)
        self.floor_31.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_31.setObjectName(_fromUtf8("floor_31"))
        self.floor_32 = QtGui.QLabel(self.groupBox_5)
        self.floor_32.setGeometry(QtCore.QRect(600, 120, 60, 60))
        self.floor_32.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_32.setTextFormat(QtCore.Qt.PlainText)
        self.floor_32.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_32.setObjectName(_fromUtf8("floor_32"))
        self.floor_33 = QtGui.QLabel(self.groupBox_5)
        self.floor_33.setGeometry(QtCore.QRect(660, 120, 60, 60))
        self.floor_33.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_33.setTextFormat(QtCore.Qt.PlainText)
        self.floor_33.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_33.setObjectName(_fromUtf8("floor_33"))
        self.floor_34 = QtGui.QLabel(self.groupBox_5)
        self.floor_34.setGeometry(QtCore.QRect(660, 20, 60, 60))
        self.floor_34.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_34.setTextFormat(QtCore.Qt.PlainText)
        self.floor_34.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_34.setObjectName(_fromUtf8("floor_34"))
        self.floor_39 = QtGui.QLabel(self.groupBox_5)
        self.floor_39.setGeometry(QtCore.QRect(660, 200, 60, 60))
        self.floor_39.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_39.setTextFormat(QtCore.Qt.PlainText)
        self.floor_39.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_39.setObjectName(_fromUtf8("floor_39"))
        self.floor_40 = QtGui.QLabel(self.groupBox_5)
        self.floor_40.setGeometry(QtCore.QRect(720, 200, 60, 60))
        self.floor_40.setStyleSheet(_fromUtf8("border: 1px solid gray;\n"
"background-color: rgb(255, 255, 255);"))
        self.floor_40.setTextFormat(QtCore.Qt.PlainText)
        self.floor_40.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_40.setObjectName(_fromUtf8("floor_40"))
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.fan12Button = QtGui.QPushButton(self.groupBox_4)
        self.fan12Button.setMinimumSize(QtCore.QSize(100, 60))
        self.fan12Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fan12Button.setStyleSheet(_fromUtf8(""))
        self.fan12Button.setCheckable(True)
        self.fan12Button.setObjectName(_fromUtf8("fan12Button"))
        self.verticalLayout_5.addWidget(self.fan12Button)
        self.fan34Button = QtGui.QPushButton(self.groupBox_4)
        self.fan34Button.setMinimumSize(QtCore.QSize(100, 60))
        self.fan34Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fan34Button.setCheckable(True)
        self.fan34Button.setObjectName(_fromUtf8("fan34Button"))
        self.verticalLayout_5.addWidget(self.fan34Button)
        self.fanControlRoomButton = QtGui.QPushButton(self.groupBox_4)
        self.fanControlRoomButton.setMinimumSize(QtCore.QSize(100, 60))
        self.fanControlRoomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fanControlRoomButton.setCheckable(True)
        self.fanControlRoomButton.setObjectName(_fromUtf8("fanControlRoomButton"))
        self.verticalLayout_5.addWidget(self.fanControlRoomButton)
        self.glowButton = QtGui.QPushButton(self.groupBox_4)
        self.glowButton.setMinimumSize(QtCore.QSize(100, 60))
        self.glowButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.glowButton.setCheckable(True)
        self.glowButton.setObjectName(_fromUtf8("glowButton"))
        self.verticalLayout_5.addWidget(self.glowButton)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.stroboButton = QtGui.QPushButton(self.groupBox_4)
        self.stroboButton.setMinimumSize(QtCore.QSize(100, 60))
        self.stroboButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stroboButton.setCheckable(True)
        self.stroboButton.setObjectName(_fromUtf8("stroboButton"))
        self.verticalLayout_6.addWidget(self.stroboButton)
        self.hotZoneButton = QtGui.QPushButton(self.groupBox_4)
        self.hotZoneButton.setMinimumSize(QtCore.QSize(100, 60))
        self.hotZoneButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hotZoneButton.setCheckable(True)
        self.hotZoneButton.setObjectName(_fromUtf8("hotZoneButton"))
        self.verticalLayout_6.addWidget(self.hotZoneButton)
        self.louverButton = QtGui.QPushButton(self.groupBox_4)
        self.louverButton.setMinimumSize(QtCore.QSize(100, 60))
        self.louverButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.louverButton.setCheckable(True)
        self.louverButton.setObjectName(_fromUtf8("louverButton"))
        self.verticalLayout_6.addWidget(self.louverButton)
        self.smokeButton = QtGui.QPushButton(self.groupBox_4)
        self.smokeButton.setMinimumSize(QtCore.QSize(100, 60))
        self.smokeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.smokeButton.setCheckable(True)
        self.smokeButton.setObjectName(_fromUtf8("smokeButton"))
        self.verticalLayout_6.addWidget(self.smokeButton)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.polygonLight1Button = QtGui.QPushButton(self.groupBox_3)
        self.polygonLight1Button.setMinimumSize(QtCore.QSize(100, 60))
        self.polygonLight1Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.polygonLight1Button.setCheckable(True)
        self.polygonLight1Button.setObjectName(_fromUtf8("polygonLight1Button"))
        self.verticalLayout_3.addWidget(self.polygonLight1Button)
        self.polygonLight2Button = QtGui.QPushButton(self.groupBox_3)
        self.polygonLight2Button.setMinimumSize(QtCore.QSize(100, 60))
        self.polygonLight2Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.polygonLight2Button.setCheckable(True)
        self.polygonLight2Button.setObjectName(_fromUtf8("polygonLight2Button"))
        self.verticalLayout_3.addWidget(self.polygonLight2Button)
        self.polygonLight3Button = QtGui.QPushButton(self.groupBox_3)
        self.polygonLight3Button.setMinimumSize(QtCore.QSize(100, 60))
        self.polygonLight3Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.polygonLight3Button.setCheckable(True)
        self.polygonLight3Button.setObjectName(_fromUtf8("polygonLight3Button"))
        self.verticalLayout_3.addWidget(self.polygonLight3Button)
        self.hotZoneLightButton = QtGui.QPushButton(self.groupBox_3)
        self.hotZoneLightButton.setMinimumSize(QtCore.QSize(100, 60))
        self.hotZoneLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hotZoneLightButton.setCheckable(True)
        self.hotZoneLightButton.setObjectName(_fromUtf8("hotZoneLightButton"))
        self.verticalLayout_3.addWidget(self.hotZoneLightButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stressRoomLightButton = QtGui.QPushButton(self.groupBox_3)
        self.stressRoomLightButton.setMinimumSize(QtCore.QSize(100, 60))
        self.stressRoomLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stressRoomLightButton.setCheckable(True)
        self.stressRoomLightButton.setObjectName(_fromUtf8("stressRoomLightButton"))
        self.verticalLayout_4.addWidget(self.stressRoomLightButton)
        self.infraLightButton = QtGui.QPushButton(self.groupBox_3)
        self.infraLightButton.setMinimumSize(QtCore.QSize(100, 60))
        self.infraLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.infraLightButton.setCheckable(True)
        self.infraLightButton.setObjectName(_fromUtf8("infraLightButton"))
        self.verticalLayout_4.addWidget(self.infraLightButton)
        self.controlRoomLightButton = QtGui.QPushButton(self.groupBox_3)
        self.controlRoomLightButton.setMinimumSize(QtCore.QSize(100, 60))
        self.controlRoomLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.controlRoomLightButton.setCheckable(True)
        self.controlRoomLightButton.setObjectName(_fromUtf8("controlRoomLightButton"))
        self.verticalLayout_4.addWidget(self.controlRoomLightButton)
        self.helpLightButton = QtGui.QPushButton(self.groupBox_3)
        self.helpLightButton.setMinimumSize(QtCore.QSize(100, 60))
        self.helpLightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.helpLightButton.setCheckable(True)
        self.helpLightButton.setObjectName(_fromUtf8("helpLightButton"))
        self.verticalLayout_4.addWidget(self.helpLightButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.verticalLayout_7.addWidget(self.radioButton_10)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.verticalLayout_7.addWidget(self.radioButton_6)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.verticalLayout_7.addWidget(self.radioButton_9)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.verticalLayout_7.addWidget(self.radioButton_8)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.verticalLayout_7.addWidget(self.radioButton_7)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_7.addWidget(self.radioButton_5)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_7.addWidget(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_7.addWidget(self.radioButton_3)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_7.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_7.addWidget(self.radioButton)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.volumeSlider = QtGui.QSlider(self.groupBox)
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.horizontalLayout_16.addWidget(self.volumeSlider)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.pushButton_19 = QtGui.QPushButton(self.groupBox)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.verticalLayout_8.addWidget(self.pushButton_19)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButton_22 = QtGui.QPushButton(self.groupBox)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.horizontalLayout_15.addWidget(self.pushButton_22)
        self.pushButton_23 = QtGui.QPushButton(self.groupBox)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.horizontalLayout_15.addWidget(self.pushButton_23)
        self.pushButton_21 = QtGui.QPushButton(self.groupBox)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.horizontalLayout_15.addWidget(self.pushButton_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.pushButton_20 = QtGui.QPushButton(self.groupBox)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.verticalLayout_8.addWidget(self.pushButton_20)
        self.horizontalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_6 = QtGui.QGroupBox(self.tabPolygon)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_6)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.verticalLayout_9.addWidget(self.lcdNumber)
        self.emergencyButton = QtGui.QPushButton(self.groupBox_6)
        self.emergencyButton.setMinimumSize(QtCore.QSize(0, 87))
        self.emergencyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.emergencyButton.setObjectName(_fromUtf8("emergencyButton"))
        self.verticalLayout_9.addWidget(self.emergencyButton)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.startButton = QtGui.QPushButton(self.groupBox_6)
        self.startButton.setMinimumSize(QtCore.QSize(0, 100))
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_17.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.groupBox_6)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 100))
        self.stopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_17.addWidget(self.stopButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.ptabWidget.addTab(self.tabPolygon, _fromUtf8(""))
        self.tabPerson = QtGui.QWidget()
        self.tabPerson.setObjectName(_fromUtf8("tabPerson"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tabPerson)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabPerson)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_20.addWidget(self.label_2)
        self.searchPersonLineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.searchPersonLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.searchPersonLineEdit.setObjectName(_fromUtf8("searchPersonLineEdit"))
        self.horizontalLayout_20.addWidget(self.searchPersonLineEdit)
        self.addPersonButton = QtGui.QPushButton(self.groupBox_7)
        self.addPersonButton.setMinimumSize(QtCore.QSize(120, 40))
        self.addPersonButton.setObjectName(_fromUtf8("addPersonButton"))
        self.horizontalLayout_20.addWidget(self.addPersonButton)
        self.delPersonButton = QtGui.QPushButton(self.groupBox_7)
        self.delPersonButton.setMinimumSize(QtCore.QSize(120, 40))
        self.delPersonButton.setObjectName(_fromUtf8("delPersonButton"))
        self.horizontalLayout_20.addWidget(self.delPersonButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.personTableView = QtGui.QTableView(self.groupBox_7)
        self.personTableView.setObjectName(_fromUtf8("personTableView"))
        self.verticalLayout_16.addWidget(self.personTableView)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_24 = QtGui.QGroupBox(self.tabPerson)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.horizontalLayout_24)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.addMemberButton = QtGui.QPushButton(self.horizontalLayout_24)
        self.addMemberButton.setMinimumSize(QtCore.QSize(125, 40))
        self.addMemberButton.setObjectName(_fromUtf8("addMemberButton"))
        self.horizontalLayout_22.addWidget(self.addMemberButton)
        self.delMemberButton = QtGui.QPushButton(self.horizontalLayout_24)
        self.delMemberButton.setMinimumSize(QtCore.QSize(125, 40))
        self.delMemberButton.setObjectName(_fromUtf8("delMemberButton"))
        self.horizontalLayout_22.addWidget(self.delMemberButton)
        self.updateMemberButton = QtGui.QPushButton(self.horizontalLayout_24)
        self.updateMemberButton.setMinimumSize(QtCore.QSize(125, 40))
        self.updateMemberButton.setObjectName(_fromUtf8("updateMemberButton"))
        self.horizontalLayout_22.addWidget(self.updateMemberButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_22)
        self.memberTableView = QtGui.QTableView(self.horizontalLayout_24)
        self.memberTableView.setObjectName(_fromUtf8("memberTableView"))
        self.verticalLayout_18.addWidget(self.memberTableView)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.saveTrainingButton = QtGui.QPushButton(self.horizontalLayout_24)
        self.saveTrainingButton.setMinimumSize(QtCore.QSize(125, 40))
        self.saveTrainingButton.setObjectName(_fromUtf8("saveTrainingButton"))
        self.horizontalLayout_23.addWidget(self.saveTrainingButton)
        self.delTrainingButton = QtGui.QPushButton(self.horizontalLayout_24)
        self.delTrainingButton.setMinimumSize(QtCore.QSize(125, 40))
        self.delTrainingButton.setObjectName(_fromUtf8("delTrainingButton"))
        self.horizontalLayout_23.addWidget(self.delTrainingButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21.addLayout(self.verticalLayout_18)
        self.verticalLayout_13.addWidget(self.horizontalLayout_24)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.ptabWidget.addTab(self.tabPerson, _fromUtf8(""))
        self.tabTraining = QtGui.QWidget()
        self.tabTraining.setObjectName(_fromUtf8("tabTraining"))
        self.trainingTableView = QtGui.QTableView(self.tabTraining)
        self.trainingTableView.setGeometry(QtCore.QRect(55, 131, 1111, 571))
        self.trainingTableView.setObjectName(_fromUtf8("trainingTableView"))
        self.printTrainingButton = QtGui.QPushButton(self.tabTraining)
        self.printTrainingButton.setGeometry(QtCore.QRect(60, 70, 91, 24))
        self.printTrainingButton.setObjectName(_fromUtf8("printTrainingButton"))
        self.ptabWidget.addTab(self.tabTraining, _fromUtf8(""))
        self.verticalLayout.addWidget(self.ptabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionItem_1 = QtGui.QAction(MainWindow)
        self.actionItem_1.setObjectName(_fromUtf8("actionItem_1"))
        self.actionItem_2 = QtGui.QAction(MainWindow)
        self.actionItem_2.setObjectName(_fromUtf8("actionItem_2"))
        self.actionItem_3 = QtGui.QAction(MainWindow)
        self.actionItem_3.setObjectName(_fromUtf8("actionItem_3"))
        self.actionO_aplikaci = QtGui.QAction(MainWindow)
        self.actionO_aplikaci.setObjectName(_fromUtf8("actionO_aplikaci"))
        self.menuMenu.addAction(self.actionItem_1)
        self.menuMenu.addAction(self.actionItem_2)
        self.menuMenu.addAction(self.actionItem_3)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionO_aplikaci)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.ptabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Polygon Teplice", None))
        self.floor_02.setText(_translate("MainWindow", "2", None))
        self.floor_03.setText(_translate("MainWindow", "3", None))
        self.floor_04.setText(_translate("MainWindow", "4", None))
        self.floor_05.setText(_translate("MainWindow", "5", None))
        self.floor_06.setText(_translate("MainWindow", "6", None))
        self.floor_07.setText(_translate("MainWindow", "7", None))
        self.floor_08.setText(_translate("MainWindow", "8", None))
        self.floor_09.setText(_translate("MainWindow", "9", None))
        self.floor_10.setText(_translate("MainWindow", "10", None))
        self.floor_11.setText(_translate("MainWindow", "11", None))
        self.floor_12.setText(_translate("MainWindow", "12", None))
        self.floor_13.setText(_translate("MainWindow", "13", None))
        self.floor_14.setText(_translate("MainWindow", "14", None))
        self.floor_15.setText(_translate("MainWindow", "15", None))
        self.floor_16.setText(_translate("MainWindow", "16", None))
        self.floor_17.setText(_translate("MainWindow", "17", None))
        self.floor_18.setText(_translate("MainWindow", "18", None))
        self.floor_19.setText(_translate("MainWindow", "19", None))
        self.floor_20.setText(_translate("MainWindow", "20", None))
        self.floor_01.setText(_translate("MainWindow", "1", None))
        self.floor_21.setText(_translate("MainWindow", "21", None))
        self.floor_22.setText(_translate("MainWindow", "22", None))
        self.floor_23.setText(_translate("MainWindow", "23", None))
        self.floor_24.setText(_translate("MainWindow", "24", None))
        self.floor_25.setText(_translate("MainWindow", "25", None))
        self.floor_26.setText(_translate("MainWindow", "26", None))
        self.floor_27.setText(_translate("MainWindow", "27", None))
        self.floor_28.setText(_translate("MainWindow", "28", None))
        self.floor_29.setText(_translate("MainWindow", "29", None))
        self.floor_30.setText(_translate("MainWindow", "30", None))
        self.floor_31.setText(_translate("MainWindow", "31", None))
        self.floor_32.setText(_translate("MainWindow", "32", None))
        self.floor_33.setText(_translate("MainWindow", "33", None))
        self.floor_34.setText(_translate("MainWindow", "34", None))
        self.floor_35.setText(_translate("MainWindow", "35", None))
        self.floor_36.setText(_translate("MainWindow", "36", None))
        self.floor_37.setText(_translate("MainWindow", "37", None))
        self.floor_38.setText(_translate("MainWindow", "38", None))
        self.floor_39.setText(_translate("MainWindow", "39", None))
        self.floor_40.setText(_translate("MainWindow", "40", None))
        self.floor_41.setText(_translate("MainWindow", "41", None))
        self.floor_42.setText(_translate("MainWindow", "42", None))
        self.floor_43.setText(_translate("MainWindow", "43", None))
        self.floor_44.setText(_translate("MainWindow", "44", None))
        self.floor_45.setText(_translate("MainWindow", "45", None))
        self.floor_46.setText(_translate("MainWindow", "46", None))
        self.floor_47.setText(_translate("MainWindow", "47", None))
        self.floor_48.setText(_translate("MainWindow", "48", None))
        self.floor_49.setText(_translate("MainWindow", "49", None))
        self.floor_50.setText(_translate("MainWindow", "50", None))
        self.floor_51.setText(_translate("MainWindow", "51", None))
        self.floor_52.setText(_translate("MainWindow", "52", None))
        self.floor_53.setText(_translate("MainWindow", "53", None))
        self.floor_54.setText(_translate("MainWindow", "54", None))
        self.floor_55.setText(_translate("MainWindow", "55", None))
        self.floor_56.setText(_translate("MainWindow", "56", None))
        self.floor_57.setText(_translate("MainWindow", "57", None))
        self.floor_58.setText(_translate("MainWindow", "58", None))
        self.floor_59.setText(_translate("MainWindow", "59", None))
        self.floor_60.setText(_translate("MainWindow", "60", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Technologie", None))
        self.fan12Button.setText(_translate("MainWindow", "Ventilátor 1,2", None))
        self.fan34Button.setText(_translate("MainWindow", "Ventilátor 3,4", None))
        self.fanControlRoomButton.setText(_translate("MainWindow", "Ventilátor VELÍN", None))
        self.glowButton.setText(_translate("MainWindow", "Žhavení zadýmení", None))
        self.stroboButton.setText(_translate("MainWindow", "Záblesky", None))
        self.hotZoneButton.setText(_translate("MainWindow", "Teplá zóna", None))
        self.louverButton.setText(_translate("MainWindow", "Žaluzie", None))
        self.smokeButton.setText(_translate("MainWindow", "Zadýmení", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Světla", None))
        self.polygonLight1Button.setText(_translate("MainWindow", "Světla Polygon", None))
        self.polygonLight2Button.setText(_translate("MainWindow", "Světla Polygon", None))
        self.polygonLight3Button.setText(_translate("MainWindow", "Světla Polygon", None))
        self.hotZoneLightButton.setText(_translate("MainWindow", "Světla Teplá zóna", None))
        self.stressRoomLightButton.setText(_translate("MainWindow", "Zátěžová míst.", None))
        self.infraLightButton.setText(_translate("MainWindow", "Infra osvětlení", None))
        self.controlRoomLightButton.setText(_translate("MainWindow", "Světla VELÍN", None))
        self.helpLightButton.setText(_translate("MainWindow", "Pomocná světla", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kamery", None))
        self.radioButton_10.setText(_translate("MainWindow", "Kamera 1", None))
        self.radioButton_6.setText(_translate("MainWindow", "Kamera 2", None))
        self.radioButton_9.setText(_translate("MainWindow", "Kamera 3", None))
        self.radioButton_8.setText(_translate("MainWindow", "Kamera 4", None))
        self.radioButton_7.setText(_translate("MainWindow", "Kamera 5", None))
        self.radioButton_5.setText(_translate("MainWindow", "Kamera 6", None))
        self.radioButton_4.setText(_translate("MainWindow", "Kamera 7", None))
        self.radioButton_3.setText(_translate("MainWindow", "Kamera 8", None))
        self.radioButton_2.setText(_translate("MainWindow", "Kamera 9", None))
        self.radioButton.setText(_translate("MainWindow", "Automat", None))
        self.groupBox.setTitle(_translate("MainWindow", "Zvuky", None))
        self.pushButton_19.setText(_translate("MainWindow", "Zvukové efekty", None))
        self.pushButton_22.setText(_translate("MainWindow", "Odposlech 1", None))
        self.pushButton_23.setText(_translate("MainWindow", "Odposlech 2", None))
        self.pushButton_21.setText(_translate("MainWindow", "Odposlech 3", None))
        self.pushButton_20.setText(_translate("MainWindow", "Mikrofon", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Obsluha", None))
        self.emergencyButton.setText(_translate("MainWindow", "Nouzové tlačítko", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabPolygon), _translate("MainWindow", "Polygon", None))
        self.label_2.setText(_translate("MainWindow", "Vyhledat osobu", None))
        self.addPersonButton.setText(_translate("MainWindow", "Založit osobu", None))
        self.delPersonButton.setText(_translate("MainWindow", "Smazat osobu", None))
        self.horizontalLayout_24.setTitle(_translate("MainWindow", "Cvičící osoby", None))
        self.addMemberButton.setText(_translate("MainWindow", "Přidat cvičence", None))
        self.delMemberButton.setText(_translate("MainWindow", "Smazat cvičence", None))
        self.updateMemberButton.setText(_translate("MainWindow", "Upravit cvičence", None))
        self.saveTrainingButton.setText(_translate("MainWindow", "Uložit cvičení", None))
        self.delTrainingButton.setText(_translate("MainWindow", "Smazat cvičení", None))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabPerson), _translate("MainWindow", "Osoby", None))
        self.printTrainingButton.setText(_translate("MainWindow", "Tisk protokolu", None))
        self.ptabWidget.setTabText(self.ptabWidget.indexOf(self.tabTraining), _translate("MainWindow", "Cvičení", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionItem_1.setText(_translate("MainWindow", "Item 1", None))
        self.actionItem_2.setText(_translate("MainWindow", "Item 2", None))
        self.actionItem_3.setText(_translate("MainWindow", "Item 3", None))
        self.actionO_aplikaci.setText(_translate("MainWindow", "O aplikaci", None))


    

class PersonForm(QtGui.QDialog):
	def __init__(self, model):
		QtGui.QDialog.__init__(self)
		#super(PersonForm, self).__init__(parent)
		self.model = model
		self.setupUi(self)

	def setupUi(self, PersonForm):
		PersonForm.setObjectName(_fromUtf8("Dialog"))
		PersonForm.resize(404, 341)
		self.buttonBox = QtGui.QDialogButtonBox(PersonForm)
		self.buttonBox.setGeometry(QtCore.QRect(40, 280, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.label = QtGui.QLabel(PersonForm)
		self.label.setGeometry(QtCore.QRect(20, 30, 53, 15))
		self.label.setObjectName(_fromUtf8("label"))
		self.label_2 = QtGui.QLabel(PersonForm)
		self.label_2.setGeometry(QtCore.QRect(20, 80, 53, 15))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.label_3 = QtGui.QLabel(PersonForm)
		self.label_3.setGeometry(QtCore.QRect(20, 130, 53, 15))
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.label_4 = QtGui.QLabel(PersonForm)
		self.label_4.setGeometry(QtCore.QRect(20, 180, 91, 16))
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.lineEdit = QtGui.QLineEdit(PersonForm)
		self.lineEdit.setGeometry(QtCore.QRect(100, 30, 113, 23))
		self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
		self.lineEdit_2 = QtGui.QLineEdit(PersonForm)
		self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 113, 23))
		self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
		self.lineEdit_3 = QtGui.QLineEdit(PersonForm)
		self.lineEdit_3.setGeometry(QtCore.QRect(100, 130, 113, 23))
		self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
		self.lineEdit_4 = QtGui.QLineEdit(PersonForm)
		self.lineEdit_4.setGeometry(QtCore.QRect(120, 180, 113, 23))
		self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
		self.label_5 = QtGui.QLabel(PersonForm)
		self.label_5.setGeometry(QtCore.QRect(20, 230, 71, 16))
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.lineEdit_5 = QtGui.QLineEdit(PersonForm)
		self.lineEdit_5.setGeometry(QtCore.QRect(120, 230, 113, 23))
		self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))

		self.mapper = QtGui.QDataWidgetMapper(self)
		self.mapper.setSubmitPolicy(QtGui.QDataWidgetMapper.AutoSubmit)
		self.mapper.setModel(self.model)
		self.mapper.addMapping(self.lineEdit,1)
		self.mapper.addMapping(self.lineEdit_2,2)
		self.mapper.addMapping(self.lineEdit_3,3)
		self.mapper.addMapping(self.lineEdit_4,4)
		self.mapper.addMapping(self.lineEdit_5,5)

		row = self.model.rowCount()
		self.mapper.submit()
		self.model.insertRow(row)
		self.mapper.setCurrentIndex(row)

		self.retranslateUi(PersonForm)
		self.buttonBox.rejected.connect(self.reject)
		self.buttonBox.accepted.connect(self.addPerson)

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
		self.label.setText(_translate("Dialog", "Jmeno", None))
		self.label_2.setText(_translate("Dialog", "Prijmeni", None))
		self.label_3.setText(_translate("Dialog", "Datum narozeni", None))
		self.label_4.setText(_translate("Dialog", "OEC", None))
		self.label_5.setText(_translate("Dialog", "Organizace", None))

	def addPerson(self):
		row = self.mapper.currentIndex()
		self.mapper.submit()
		self.mapper.setCurrentIndex(row)
		self.model.submitAll()
		self.accept()


class MemberForm(QtGui.QDialog):
	def __init__(self, model, row):
		QtGui.QDialog.__init__(self)
		#super(PersonForm, self).__init__(parent)
		self.model = model
		self.row = row
		self.setupUi(self)

	def setupUi(self, MemberForm):
		MemberForm.setObjectName(_fromUtf8("Dialog"))
		MemberForm.resize(404, 341)
		self.buttonBox = QtGui.QDialogButtonBox(MemberForm)
		self.buttonBox.setGeometry(QtCore.QRect(40, 280, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.label = QtGui.QLabel(MemberForm)
		self.label.setGeometry(QtCore.QRect(70, 20, 231, 41))
		font = QtGui.QFont()
		font.setPointSize(14)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setText(_fromUtf8(""))
		self.label.setObjectName(_fromUtf8("label"))
		self.label_2 = QtGui.QLabel(MemberForm)
		self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 16))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.label_3 = QtGui.QLabel(MemberForm)
		self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 16))
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.label_4 = QtGui.QLabel(MemberForm)
		self.label_4.setGeometry(QtCore.QRect(20, 180, 71, 16))
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.validator = QtGui.QIntValidator(0,999,self)
		self.lineEdit_2 = QtGui.QLineEdit(MemberForm)
		self.lineEdit_2.setValidator(self.validator)
		self.lineEdit_2.setGeometry(QtCore.QRect(120, 80, 113, 23))
		self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
		self.lineEdit_3 = QtGui.QLineEdit(MemberForm)
		self.lineEdit_3.setValidator(self.validator)
		self.lineEdit_3.setGeometry(QtCore.QRect(120, 130, 113, 23))
		self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
		self.lineEdit_4 = QtGui.QLineEdit(MemberForm)
		self.lineEdit_4.setValidator(self.validator)
		self.lineEdit_4.setGeometry(QtCore.QRect(120, 180, 113, 23))
		self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))

		
		if self.row < 0:self.row=0
		name = self.model.record(self.row).value("name").toString()
		volume = self.model.record(self.row).value("volume").toString()
		press_start = self.model.record(self.row).value("press_start").toString()
		press_end = self.model.record(self.row).value("press_end").toString()
		self.label.setText(name)
		self.lineEdit_2.setText(volume)
		self.lineEdit_3.setText(press_start)
		self.lineEdit_4.setText(press_end)

		self.retranslateUi(MemberForm)
		self.buttonBox.rejected.connect(self.reject)
		self.buttonBox.accepted.connect(self.updateMember)  

	def retranslateUi(self, Dialog):
		Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
		self.label_2.setText(_translate("Dialog", "Objem láhve", None))
		self.label_3.setText(_translate("Dialog", "Tlak na začátku", None))
		self.label_4.setText(_translate("Dialog", "Tlak na konci", None))

	def updateMember(self):
		query = self.model.query()
		idmember = self.model.record(self.row).value("idMember").toInt()[0]
		volume = self.lineEdit_2.text()
		press_start =  self.lineEdit_3.text()
		press_end =  self.lineEdit_4.text()
		volume = volume.toInt()[0]
		press_start = press_start.toInt()[0]
		press_end =  press_end.toInt()[0]
		query.exec_("UPDATE member SET volume=%d, press_start=%d, press_end=%d WHERE idMember=%d" % (volume,press_start,press_end,idmember))
		self.model.view()
		self.accept()